//! SSH tunnel integration tests.
//!
//! These run against the containers in `docker-compose.test.yml`:
//!
//!     docker compose -f docker-compose.test.yml up -d --wait
//!
//! When the containers are not running the tests skip, so `cargo test` works on
//! a laptop without Docker. CI sets `DBSYNC_REQUIRE_CONTAINERS=1`, which turns
//! a skip into a failure — otherwise a broken harness would look like a green
//! build forever.

use std::sync::Arc;
use std::time::Duration;

use db_sync_engine::ssh::{
    AcceptAllHostKeys, HostKeyInfo, HostKeyVerifier, RusshTunnelProvider, SshCredentials,
    StoreHostKeyVerifier, TunnelError, TunnelProvider,
};
use db_sync_engine::sshconn::{SshAuth, SshConfig, SshEndpoint};
use db_sync_engine::store::Store;
use tokio::io::AsyncReadExt;
use tokio::net::TcpStream;

const SSH_PORT: u16 = 12222;
const SSH_USER: &str = "tunnel";

/// Path to the throwaway key generated by the test setup.
fn key_path() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../tests/fixtures/ssh/id_ed25519"
    )
    .to_string()
}

/// True when the ssh container is reachable.
async fn containers_up() -> bool {
    tokio::time::timeout(
        Duration::from_secs(2),
        TcpStream::connect(("127.0.0.1", SSH_PORT)),
    )
    .await
    .map(|r| r.is_ok())
    .unwrap_or(false)
}

/// Skip unless CI demands the containers be present.
macro_rules! require_containers {
    () => {
        if !containers_up().await {
            if std::env::var("DBSYNC_REQUIRE_CONTAINERS").is_ok() {
                panic!(
                    "test containers are required but not reachable on port {SSH_PORT}; \
                     run: docker compose -f docker-compose.test.yml up -d --wait"
                );
            }
            eprintln!("skipping: test containers not running");
            return;
        }
    };
}

fn ssh_config() -> SshConfig {
    SshConfig {
        endpoint: SshEndpoint {
            host: "127.0.0.1".into(),
            port: SSH_PORT,
            user: SSH_USER.into(),
            auth: SshAuth::KeyFile {
                path: key_path(),
                passphrase_in_keychain: false,
            },
        },
        jump_host: None,
    }
}

fn provider() -> RusshTunnelProvider {
    RusshTunnelProvider::new(Arc::new(AcceptAllHostKeys))
}

/// Read enough of MySQL's greeting to prove real protocol bytes crossed the
/// tunnel, rather than just that a TCP connection was accepted locally.
async fn read_mysql_handshake(port: u16) -> Vec<u8> {
    let mut socket = tokio::time::timeout(
        Duration::from_secs(10),
        TcpStream::connect(("127.0.0.1", port)),
    )
    .await
    .expect("connect timed out")
    .expect("connect failed");

    let mut buf = [0u8; 5];
    tokio::time::timeout(Duration::from_secs(10), socket.read_exact(&mut buf))
        .await
        .expect("read timed out")
        .expect("read failed");

    buf.to_vec()
}

#[tokio::test]
async fn tunnel_forwards_mysql_traffic() {
    require_containers!();

    let handle = provider()
        .open(&ssh_config(), &SshCredentials::default(), "mysql", 3306)
        .await
        .expect("tunnel should open");

    assert_ne!(handle.local_port(), 0);
    assert!(!handle.is_closed());

    let greeting = read_mysql_handshake(handle.local_port()).await;

    // MySQL's initial handshake packet: 3-byte length, 1-byte sequence 0, then
    // the protocol version (10).
    assert_eq!(greeting[3], 0, "first packet must have sequence number 0");
    assert_eq!(
        greeting[4], 10,
        "expected MySQL protocol version 10, got {greeting:?}"
    );
}

#[tokio::test]
async fn tunnel_forwards_postgres_traffic() {
    require_containers!();

    let handle = provider()
        .open(&ssh_config(), &SshCredentials::default(), "postgres", 5432)
        .await
        .expect("tunnel should open");

    // PostgreSQL says nothing until spoken to, so send an SSLRequest and check
    // the single-byte reply ('S' or 'N').
    let mut socket = TcpStream::connect(("127.0.0.1", handle.local_port()))
        .await
        .expect("connect through tunnel");

    use tokio::io::AsyncWriteExt;
    let mut msg = Vec::new();
    msg.extend_from_slice(&8u32.to_be_bytes());
    msg.extend_from_slice(&80877103u32.to_be_bytes()); // SSLRequest magic
    socket.write_all(&msg).await.expect("write SSLRequest");

    let mut reply = [0u8; 1];
    tokio::time::timeout(Duration::from_secs(10), socket.read_exact(&mut reply))
        .await
        .expect("read timed out")
        .expect("read failed");

    assert!(
        reply[0] == b'S' || reply[0] == b'N',
        "expected an SSL negotiation reply, got {:?}",
        reply[0] as char
    );
}

#[tokio::test]
async fn two_tunnels_get_distinct_ports() {
    require_containers!();

    let a = provider()
        .open(&ssh_config(), &SshCredentials::default(), "mysql", 3306)
        .await
        .expect("first tunnel");
    let b = provider()
        .open(&ssh_config(), &SshCredentials::default(), "postgres", 5432)
        .await
        .expect("second tunnel");

    // The bash predecessor hardcoded 13306/13307 and collided whenever two runs
    // overlapped.
    assert_ne!(
        a.local_port(),
        b.local_port(),
        "concurrent tunnels must not share a port"
    );
}

#[tokio::test]
async fn closing_a_tunnel_stops_accepting_connections() {
    require_containers!();

    let handle = provider()
        .open(&ssh_config(), &SshCredentials::default(), "mysql", 3306)
        .await
        .expect("tunnel should open");
    let port = handle.local_port();

    // Works while open.
    let greeting = read_mysql_handshake(port).await;
    assert_eq!(greeting[4], 10);

    handle.close();
    assert!(handle.is_closed());

    // Give the accept loop a moment to notice cancellation and release the port.
    tokio::time::sleep(Duration::from_millis(500)).await;

    let after = tokio::time::timeout(
        Duration::from_secs(3),
        TcpStream::connect(("127.0.0.1", port)),
    )
    .await;

    let still_serving = match after {
        Ok(Ok(mut socket)) => {
            // The OS may still accept on a lingering socket; what matters is
            // that no data is forwarded.
            let mut buf = [0u8; 1];
            tokio::time::timeout(Duration::from_secs(2), socket.read_exact(&mut buf))
                .await
                .is_ok_and(|r| r.is_ok())
        }
        _ => false,
    };

    assert!(
        !still_serving,
        "a closed tunnel must not keep forwarding traffic"
    );
}

#[tokio::test]
async fn probe_reports_the_host_key_fingerprint() {
    require_containers!();

    let probe = provider()
        .probe(&ssh_config(), &SshCredentials::default())
        .await
        .expect("probe should succeed");

    assert_eq!(probe.authenticated_as, SSH_USER);
    assert!(
        probe.host_key.fingerprint.starts_with("SHA256:"),
        "fingerprint should be SHA256, got {}",
        probe.host_key.fingerprint
    );
    assert!(
        !probe.host_key.algorithm.is_empty(),
        "host key algorithm must be reported so the user can verify it"
    );
}

#[tokio::test]
async fn wrong_key_fails_authentication() {
    require_containers!();

    let mut config = ssh_config();
    config.endpoint.auth = SshAuth::KeyFile {
        path: "/nonexistent/key".into(),
        passphrase_in_keychain: false,
    };

    let err = provider()
        .open(&config, &SshCredentials::default(), "mysql", 3306)
        .await
        .expect_err("a missing key must not silently succeed");

    assert!(
        matches!(err, TunnelError::KeyFile { .. }),
        "expected a key-file error, got {err:?}"
    );
}

#[tokio::test]
async fn unreachable_host_is_reported_as_a_connect_error() {
    require_containers!();

    let mut config = ssh_config();
    // Reserved for documentation; guaranteed not to answer.
    config.endpoint.host = "203.0.113.1".into();

    let result = tokio::time::timeout(
        Duration::from_secs(20),
        provider().open(&config, &SshCredentials::default(), "mysql", 3306),
    )
    .await;

    if let Ok(outcome) = result {
        assert!(
            matches!(outcome, Err(TunnelError::Connect { .. })),
            "expected a connect error, got {outcome:?}"
        );
    }
}

// ── Host-key pinning ────────────────────────────────────────────────────

async fn temp_store() -> (Store, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::open(dir.path().join("t.db")).await.unwrap();
    (store, dir)
}

fn key_info(fingerprint: &str) -> HostKeyInfo {
    HostKeyInfo {
        algorithm: "ssh-ed25519".into(),
        fingerprint: fingerprint.into(),
    }
}

#[tokio::test]
async fn unknown_host_key_is_refused_with_its_fingerprint() {
    let (store, _dir) = temp_store().await;
    let verifier = StoreHostKeyVerifier::new(store);

    let err = verifier
        .verify("db.example.com:22", &key_info("SHA256:aaa"))
        .await
        .expect_err("an unpinned host must not be trusted automatically");

    match err {
        TunnelError::HostKeyUnknown {
            fingerprint,
            algorithm,
            ..
        } => {
            // The fingerprint has to reach the user, or they cannot verify it.
            assert_eq!(fingerprint, "SHA256:aaa");
            assert_eq!(algorithm, "ssh-ed25519");
        }
        other => panic!("expected HostKeyUnknown, got {other:?}"),
    }
}

#[tokio::test]
async fn pinned_host_key_is_accepted() {
    let (store, _dir) = temp_store().await;
    store
        .remember_host("db.example.com:22", "ssh-ed25519", "SHA256:aaa")
        .await
        .unwrap();

    let verifier = StoreHostKeyVerifier::new(store);
    let decision = verifier
        .verify("db.example.com:22", &key_info("SHA256:aaa"))
        .await
        .expect("a pinned key must be accepted");

    assert_eq!(decision, db_sync_engine::ssh::HostKeyDecision::Known);
}

#[tokio::test]
async fn changed_host_key_is_refused_loudly() {
    let (store, _dir) = temp_store().await;
    store
        .remember_host("db.example.com:22", "ssh-ed25519", "SHA256:original")
        .await
        .unwrap();

    let verifier = StoreHostKeyVerifier::new(store);
    let err = verifier
        .verify("db.example.com:22", &key_info("SHA256:different"))
        .await
        .expect_err("a changed key is indistinguishable from a MITM and must fail");

    match err {
        TunnelError::HostKeyChanged {
            expected, actual, ..
        } => {
            assert_eq!(expected, "SHA256:original");
            assert_eq!(actual, "SHA256:different");
        }
        other => panic!("expected HostKeyChanged, got {other:?}"),
    }
}

#[tokio::test]
async fn real_connection_refuses_an_unpinned_host() {
    require_containers!();

    let (store, _dir) = temp_store().await;
    let provider = RusshTunnelProvider::new(Arc::new(StoreHostKeyVerifier::new(store)));

    let err = provider
        .open(&ssh_config(), &SshCredentials::default(), "mysql", 3306)
        .await
        .expect_err("first contact must not be trusted silently");

    // russh surfaces a handler rejection as a protocol error, but the message
    // must still carry the fingerprint the user needs to verify.
    let rendered = format!("{err:?}");
    assert!(
        rendered.contains("SHA256:") || matches!(err, TunnelError::HostKeyUnknown { .. }),
        "the fingerprint must reach the user, got {rendered}"
    );
}

#[tokio::test]
async fn real_connection_succeeds_once_the_key_is_pinned() {
    require_containers!();

    // Learn the fingerprint the way the app does: attempt, capture, pin, retry.
    let probe = provider()
        .probe(&ssh_config(), &SshCredentials::default())
        .await
        .expect("probe to learn the key");

    let (store, _dir) = temp_store().await;
    store
        .remember_host(
            &format!("127.0.0.1:{SSH_PORT}"),
            &probe.host_key.algorithm,
            &probe.host_key.fingerprint,
        )
        .await
        .unwrap();

    let provider = RusshTunnelProvider::new(Arc::new(StoreHostKeyVerifier::new(store)));
    let handle = provider
        .open(&ssh_config(), &SshCredentials::default(), "mysql", 3306)
        .await
        .expect("a pinned host must connect");

    let greeting = read_mysql_handshake(handle.local_port()).await;
    assert_eq!(greeting[4], 10);
}

#[tokio::test]
async fn repeated_open_and_close_stays_healthy() {
    require_containers!();

    // A tool that opens a tunnel per job does this all day. It is also the
    // shape that exposed the graceful-disconnect bug: sessions that vanish
    // instead of sending SSH_MSG_DISCONNECT make OpenSSH 9.8+ penalise the
    // source address until it refuses connections outright.
    for i in 0..20 {
        let handle = provider()
            .open(&ssh_config(), &SshCredentials::default(), "mysql", 3306)
            .await
            .unwrap_or_else(|e| panic!("tunnel {i} should open: {e}"));

        let greeting = read_mysql_handshake(handle.local_port()).await;
        assert_eq!(greeting[4], 10, "tunnel {i} should forward MySQL");

        handle.close();
    }
}
