// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listProfiles: () => typedError<ConnectionProfile[], CommandError>(__TAURI_INVOKE("list_profiles")),
	getProfile: (id: string) => typedError<{
	id: string,
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**  `None` means connect directly, without a tunnel. */
	ssh: SshConfig | null,
	db: DbConfig,
	tool_overrides: ToolOverrides,
	created_at: string,
	updated_at: string,
} | null, CommandError>(__TAURI_INVOKE("get_profile", { id })),
	/**
	 *  Create a profile, optionally storing its database password in the keychain.
	 * 
	 *  The password is consumed here and never echoed back.
	 */
	createProfile: (input: ProfileCreate, dbPassword: string | null) => typedError<ConnectionProfile, CommandError>(__TAURI_INVOKE("create_profile", { input, dbPassword })),
	updateProfile: (id: string, patch: ProfileUpdate_Deserialize) => typedError<ConnectionProfile, CommandError>(__TAURI_INVOKE("update_profile", { id, patch })),
	/**  Delete a profile and purge every secret belonging to it. */
	deleteProfile: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_profile", { id })),
	/**  Store or clear a profile secret. An empty value clears it. */
	setProfileSecret: (id: string, kind: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_profile_secret", { id, kind, value })),
	/**  Report whether secrets exist — never their values. */
	profileSecretStatus: (id: string) => typedError<SecretStatus, CommandError>(__TAURI_INVOKE("profile_secret_status", { id })),
	testConnection: (id: string) => typedError<TestConnectionReport, CommandError>(__TAURI_INVOKE("test_connection", { id })),
	listJobs: (limit: number) => typedError<JobRecord[], CommandError>(__TAURI_INVOKE("list_jobs", { limit })),
	/**
	 *  Cancel a running job.
	 * 
	 *  This signals the job's `CancellationToken`, which propagates into its child
	 *  processes and tunnels. Returns false when the job is not running.
	 */
	cancelJob: (jobId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("cancel_job", { jobId })),
	activeJobIds: () => typedError<string[], CommandError>(__TAURI_INVOKE("active_job_ids")),
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
};

/** Events */
export const events = {
	jobFinished: makeEvent<JobFinished>("job-finished"),
	jobProgress: makeEvent<JobProgress>("job-progress"),
};

/* Types */
export type AppInfo = {
	engine_version: string,
	store_path: string,
};

/**
 *  Error shape crossing into the webview.
 * 
 *  Carries a human-readable message and a machine-readable kind so the UI can
 *  react (e.g. highlight a duplicate name field) without string matching.
 */
export type CommandError = {
	kind: string,
	message: string,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**  `None` means connect directly, without a tunnel. */
	ssh: SshConfig | null,
	db: DbConfig,
	tool_overrides: ToolOverrides,
	created_at: string,
	updated_at: string,
};

/**
 *  Database coordinates *as seen from the SSH host* (or from this machine when
 *  `ConnectionProfile::ssh` is `None`).
 */
export type DbConfig = {
	host: string,
	port: number,
	user: string,
	database: string | null,
};

/**
 *  A supported database engine.
 * 
 *  The serde representation is snake_case and is the *single* source of truth
 *  for how these values are written to SQLite and to JSON manifests. Do not
 *  hand-write match arms mapping these to strings — use `Display`/`FromStr`.
 */
export type Engine = "mysql" | "postgres";

/**
 *  Environment classification for a connection profile.
 * 
 *  Drives colour-coding in the UI and the strictness of destructive-action
 *  confirmations — production targets require typed confirmation.
 */
export type EnvironmentTag = "prod" | "staging" | "dev";

/**
 *  Emitted when a job reaches a terminal state, so the UI can refresh history
 *  without polling.
 */
export type JobFinished = {
	job_id: string,
	outcome: string,
};

export type JobKind = "backup" | "restore" | "verify" | "sync";

export type JobOutcome = "success" | "failed" | "cancelled";

export type JobPhase = "initializing" | "ssh_connect" | "tunneling" | "introspect" | "dump_schema" | "dump_data" | "compress" | "transfer" | "restore" | "verify" | "cleanup" | "done";

/**  One progress record from a running job. */
export type JobProgress = ProgressEvent;

/**  The persisted record of one job run. */
export type JobRecord = {
	id: string,
	kind: JobKind,
	source_profile_id: string,
	dest_profile_id: string | null,
	started_at: string,
	finished_at: string | null,
	outcome: JobOutcome | null,
	artifact_path: string | null,
	/**
	 *  Serialised options, kept opaque so option shapes can evolve without a
	 *  schema migration.
	 */
	options_json: string,
	/**
	 *  Durable log. Accumulated from the event stream by [`JobContext`] — the
	 *  broadcast channel is lossy and must never be the only record.
	 */
	log: string,
};

export type LogLevel = "debug" | "info" | "warn" | "error";

export type ProfileCreate = {
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	ssh: SshConfig | null,
	db: DbConfig,
	tool_overrides?: ToolOverrides,
};

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh` is doubly-optional on purpose, and the distinction is carried by
 *  *presence*, not by value: omitting the key leaves the SSH config alone,
 *  while sending an explicit `null` clears it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate = ProfileUpdate_Serialize | ProfileUpdate_Deserialize;

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh` is doubly-optional on purpose, and the distinction is carried by
 *  *presence*, not by value: omitting the key leaves the SSH config alone,
 *  while sending an explicit `null` clears it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate_Deserialize = {
	name?: string | null,
	engine?: Engine | null,
	environment?: EnvironmentTag | null,
	ssh?: SshConfig | null,
	db?: DbConfig | null,
	tool_overrides?: ToolOverrides | null,
};

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh` is doubly-optional on purpose, and the distinction is carried by
 *  *presence*, not by value: omitting the key leaves the SSH config alone,
 *  while sending an explicit `null` clears it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate_Serialize = {
	name: string | null,
	engine: Engine | null,
	environment: EnvironmentTag | null,
	ssh?: SshConfig | null,
	db: DbConfig | null,
	tool_overrides: ToolOverrides | null,
};

/**
 *  A single point-in-time progress record.
 * 
 *  Every field beyond `job_id`/`ts`/`phase`/`level`/`message` is optional
 *  because different phases have different meaningful measurements: a schema
 *  dump reports bytes, a data dump reports per-table counts.
 */
export type ProgressEvent = {
	job_id: string,
	ts: string,
	phase: JobPhase,
	level: LogLevel,
	message: string,
	table: string | null,
	bytes_done: number | null,
	bytes_total: number | null,
	rows: number | null,
	percent: number | null,
};

/**  What the UI is allowed to know about stored secrets: whether they exist. */
export type SecretStatus = {
	has_db_password: boolean,
	has_ssh_passphrase: boolean,
};

export type SshAuth = 
/**  Use the running ssh-agent. Preferred: no key material touches us. */
{ kind: "agent" } | 
/**
 *  Use a private key file. `passphrase_in_keychain` records whether a
 *  passphrase was stored; the passphrase itself is never in this struct.
 */
{ kind: "key_file"; path: string; passphrase_in_keychain: boolean };

export type SshConfig = {
	/**  Optional single-hop ProxyJump. Chained jumps are out of scope for v1. */
	jump_host: SshEndpoint | null,
} & SshEndpoint;

export type SshEndpoint = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

export type StepResult = { status: "ok"; detail: string } | { status: "failed"; detail: string } | { status: "skipped"; detail: string };

export type TestConnectionReport = {
	ssh: StepResult,
	tunnel: StepResult,
	db_ping: StepResult,
	catalog_read: StepResult,
	server_version: string | null,
};

/**
 *  Per-profile overrides for external client binaries.
 * 
 *  We never bundle Oracle's `mysqldump` (GPLv2); binaries are discovered on the
 *  host and may be pointed at explicitly here. See DECISIONS.md.
 */
export type ToolOverrides = {
	mysqldump: string | null,
	mysql: string | null,
	mydumper: string | null,
	myloader: string | null,
	pg_dump: string | null,
	pg_dumpall: string | null,
	pg_restore: string | null,
	psql: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

