// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listProfiles: () => typedError<ConnectionProfile[], CommandError>(__TAURI_INVOKE("list_profiles")),
	getProfile: (id: string) => typedError<{
	id: string,
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**
	 *  The saved SSH connection this profile tunnels through. `None` means
	 *  connect directly, without a tunnel.
	 */
	ssh_connection_id: string | null,
	db: DbConfig,
	tool_overrides: ToolOverrides,
	created_at: string,
	updated_at: string,
} | null, CommandError>(__TAURI_INVOKE("get_profile", { id })),
	/**
	 *  Create a profile, optionally storing its database password in the keychain.
	 * 
	 *  The password is consumed here and never echoed back.
	 */
	createProfile: (input: ProfileCreate, dbPassword: string | null) => typedError<ConnectionProfile, CommandError>(__TAURI_INVOKE("create_profile", { input, dbPassword })),
	updateProfile: (id: string, patch: ProfileUpdate_Deserialize) => typedError<ConnectionProfile, CommandError>(__TAURI_INVOKE("update_profile", { id, patch })),
	/**  Delete a profile and purge every secret belonging to it. */
	deleteProfile: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_profile", { id })),
	/**  Store or clear a profile secret. An empty value clears it. */
	setProfileSecret: (id: string, kind: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_profile_secret", { id, kind, value })),
	/**  Report whether secrets exist — never their values. */
	profileSecretStatus: (id: string) => typedError<SecretStatus, CommandError>(__TAURI_INVOKE("profile_secret_status", { id })),
	listSshConnections: () => typedError<SshConnection[], CommandError>(__TAURI_INVOKE("list_ssh_connections")),
	createSshConnection: (input: SshConnectionCreate, passphrase: string | null) => typedError<SshConnection, CommandError>(__TAURI_INVOKE("create_ssh_connection", { input, passphrase })),
	/**  Edit a connection. Every profile tunnelling through it follows. */
	updateSshConnection: (id: string, patch: SshConnectionUpdate_Deserialize) => typedError<SshConnection, CommandError>(__TAURI_INVOKE("update_ssh_connection", { id, patch })),
	/**
	 *  Delete a connection and its stored passphrase.
	 * 
	 *  Refused while any profile or jump host still points at it — the error names
	 *  them, so the answer to "why not" does not need a second look.
	 */
	deleteSshConnection: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_ssh_connection", { id })),
	/**  Store or clear the passphrase protecting an SSH connection's key. */
	setSshConnectionPassphrase: (id: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_ssh_connection_passphrase", { id, value })),
	sshConnectionStatus: (id: string) => typedError<SshConnectionStatus, CommandError>(__TAURI_INVOKE("ssh_connection_status", { id })),
	/**
	 *  Connect and authenticate an SSH connection on its own, without a database.
	 * 
	 *  Never returns `Err` for an unreachable server, for the same reason
	 *  [`test_connection`] does not: a failed connection is a successful test.
	 */
	testSshConnection: (id: string) => typedError<SshReport, CommandError>(__TAURI_INVOKE("test_ssh_connection", { id })),
	/**
	 *  Test a profile, reporting each step separately.
	 * 
	 *  Never returns `Err` for an unreachable server: a failed *connection* is a
	 *  successful *test*, and the per-step detail is the whole point.
	 */
	testConnection: (id: string) => typedError<ConnectionReport, CommandError>(__TAURI_INVOKE("test_connection", { id })),
	/**
	 *  Pin a host key after the user has verified its fingerprint.
	 * 
	 *  `replace` must be set explicitly when a *different* key was already pinned —
	 *  silently overwriting is indistinguishable from accepting a MITM.
	 */
	trustHostKey: (hostPort: string, algorithm: string, fingerprint: string, replace: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("trust_host_key", { hostPort, algorithm, fingerprint, replace })),
	/**  List the databases visible to a profile's user. */
	listDatabases: (id: string) => typedError<DatabaseInfo[], CommandError>(__TAURI_INVOKE("list_databases", { id })),
	/**  List the tables in one database, with the metadata the picker needs. */
	listTables: (id: string, database: string) => typedError<TableInfo[], CommandError>(__TAURI_INVOKE("list_tables", { id, database })),
	/**
	 *  Start a backup and return its job id immediately.
	 * 
	 *  The work runs in the background; progress arrives as `JobProgress` events
	 *  and the terminal state as `JobFinished`. Blocking the command until the dump
	 *  finished would freeze the UI for the length of the job.
	 */
	startBackup: (profileId: string, request: BackupRequest) => typedError<string, CommandError>(__TAURI_INVOKE("start_backup", { profileId, request })),
	/**  Start a source-to-destination sync and return its job id. */
	startSync: (sourceId: string, destId: string, request: SyncRequest) => typedError<string, CommandError>(__TAURI_INVOKE("start_sync", { sourceId, destId, request })),
	listSyncPlans: (profileId: string) => typedError<SyncPlan[], CommandError>(__TAURI_INVOKE("list_sync_plans", { profileId })),
	createSyncPlan: (input: SyncPlanCreate) => typedError<SyncPlan, CommandError>(__TAURI_INVOKE("create_sync_plan", { input })),
	updateSyncPlan: (id: string, selections: TableSelection[]) => typedError<SyncPlan, CommandError>(__TAURI_INVOKE("update_sync_plan", { id, selections })),
	/**
	 *  Rename a table set.
	 * 
	 *  Separate from `update_sync_plan` because it must not bump the revision: a
	 *  revision means "what this set backs up changed", and a typo fix changes
	 *  nothing a schedule needs to re-examine.
	 */
	renameSyncPlan: (id: string, name: string) => typedError<SyncPlan, CommandError>(__TAURI_INVOKE("rename_sync_plan", { id, name })),
	deleteSyncPlan: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_sync_plan", { id })),
	/**
	 *  Turn a legacy `tables.conf` into a complete selection list.
	 * 
	 *  Lets an existing Bash-tool setup be carried over without retyping a couple
	 *  of hundred table names.
	 * 
	 *  `available` is the source's table list, and the file cannot be honoured
	 *  without it: the file names only what carries data, while a selection that
	 *  stays silent about a table gives it data at run time. See
	 *  [`plan::selections_from_tables_conf`]. The caller passes the introspection
	 *  it has already made rather than this connecting again, so an import is still
	 *  one click on a list the user is looking at.
	 */
	importTablesConf: (contents: string, available: string[]) => typedError<TableSelection[], CommandError>(__TAURI_INVOKE("import_tables_conf", { contents, available })),
	setSyncPlanMasking: (id: string, masking: MaskRule[]) => typedError<SyncPlan, CommandError>(__TAURI_INVOKE("set_sync_plan_masking", { id, masking })),
	/**
	 *  Show what masking would do, without running it.
	 * 
	 *  The salt appears as a bound placeholder rather than a literal, here and in
	 *  the real statements, so this output is safe to paste into a ticket.
	 */
	maskingPreview: (planId: string) => typedError<MaskingPreview, CommandError>(__TAURI_INVOKE("masking_preview", { planId })),
	backupKeyStatus: () => typedError<KeyStatus, CommandError>(__TAURI_INVOKE("backup_key_status")),
	generateBackupKey: () => typedError<KeyStatus, CommandError>(__TAURI_INVOKE("generate_backup_key")),
	setBackupKeyRecipients: (keys: string[]) => typedError<KeyStatus, CommandError>(__TAURI_INVOKE("set_backup_key_recipients", { keys })),
	/**
	 *  Write the secret key to a file and return where it went.
	 * 
	 *  The secret is deliberately **not** returned. The webview can ask for the
	 *  key to be escrowed and can be told where it landed, but there is no command
	 *  anywhere in this app that hands a secret to the frontend — the same rule
	 *  that governs database passwords. Copying it out of a file is the user's
	 *  job, and it means the value never sits in a JS string, a React state atom,
	 *  or a devtools console.
	 */
	exportBackupKeyToFile: () => typedError<string, CommandError>(__TAURI_INVOKE("export_backup_key_to_file")),
	/**  Start a restore and return its job id immediately. */
	startRestore: (profileId: string, request: RestoreRequest) => typedError<string, CommandError>(__TAURI_INVOKE("start_restore", { profileId, request })),
	backupDirectory: () => typedError<string, CommandError>(__TAURI_INVOKE("backup_directory")),
	listArtifacts: (directory: string | null) => typedError<Artifact[], CommandError>(__TAURI_INVOKE("list_artifacts", { directory })),
	/**  Hash an artifact and compare it against its manifest. */
	checkArtifact: (path: string) => typedError<IntegrityCheck, CommandError>(__TAURI_INVOKE("check_artifact", { path })),
	/**  Delete an artifact and its manifest. */
	deleteArtifact: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_artifact", { path })),
	/**  One page of job history, newest first, with the size of the whole set. */
	listJobs: (limit: number, offset: number) => typedError<JobPage, CommandError>(__TAURI_INVOKE("list_jobs", { limit, offset })),
	/**
	 *  The steps one job is made of, in order.
	 * 
	 *  Empty for a single-step job — a plain backup or restore has no shape worth
	 *  drawing — and for anything that ran before this was recorded.
	 */
	listJobSteps: (jobId: string) => typedError<JobStep[], CommandError>(__TAURI_INVOKE("list_job_steps", { jobId })),
	listPipelines: () => typedError<Pipeline[], CommandError>(__TAURI_INVOKE("list_pipelines")),
	getPipeline: (id: string) => typedError<{
	id: string,
	name: string,
	steps: PipelineStep[],
	/**
	 *  The destructive signature a human typed back when arming this pipeline
	 *  for unattended use, or `None` if it has never been armed.
	 * 
	 *  Compared against the current signature rather than trusted: see
	 *  [`Pipeline::is_armed`].
	 */
	unattended_ack?: string | null,
	created_at: string,
	updated_at: string,
} | null, CommandError>(__TAURI_INVOKE("get_pipeline", { id })),
	/**  Create a pipeline. Refused unless the whole chain is runnable. */
	createPipeline: (input: PipelineCreate) => typedError<Pipeline, CommandError>(__TAURI_INVOKE("create_pipeline", { input })),
	updatePipeline: (id: string, patch: PipelineUpdate) => typedError<Pipeline, CommandError>(__TAURI_INVOKE("update_pipeline", { id, patch })),
	/**
	 *  Authorise a destructive pipeline to run with nobody present, or withdraw it.
	 * 
	 *  `typed` is the target names as the user typed them back, newline-separated
	 *  when there is more than one. The engine compares it against what the
	 *  pipeline currently drops, so a typo authorises nothing.
	 */
	armPipeline: (id: string, typed: string | null) => typedError<Pipeline, CommandError>(__TAURI_INVOKE("arm_pipeline", { id, typed })),
	deletePipeline: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_pipeline", { id })),
	/**
	 *  Start a saved pipeline and return its job id immediately.
	 * 
	 *  `typed_confirmations` carries one name per destructive step, in the order
	 *  those steps appear. They are not checked here: each is handed to the restore
	 *  it belongs to and validated by the engine, which is the same check a
	 *  hand-built restore goes through.
	 */
	startPipeline: (id: string, typedConfirmations: string[]) => typedError<string, CommandError>(__TAURI_INVOKE("start_pipeline", { id, typedConfirmations })),
	/**
	 *  Cancel a running job.
	 * 
	 *  This signals the job's `CancellationToken`, which propagates into its child
	 *  processes and tunnels. Returns false when the job is not running.
	 */
	cancelJob: (jobId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("cancel_job", { jobId })),
	activeJobIds: () => typedError<string[], CommandError>(__TAURI_INVOKE("active_job_ids")),
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	listSchedules: () => typedError<ScheduleView[], CommandError>(__TAURI_INVOKE("list_schedules")),
	getSchedule: (id: string) => typedError<{
	schedule: Schedule,
	description: string,
	next_run_at: string | null,
	/**  True while a run started by this schedule is still going. */
	running: boolean,
} | null, CommandError>(__TAURI_INVOKE("get_schedule", { id })),
	createSchedule: (input: ScheduleCreate) => typedError<ScheduleView, CommandError>(__TAURI_INVOKE("create_schedule", { input })),
	updateSchedule: (id: string, patch: ScheduleUpdate_Deserialize) => typedError<ScheduleView, CommandError>(__TAURI_INVOKE("update_schedule", { id, patch })),
	deleteSchedule: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_schedule", { id })),
	/**
	 *  Run a schedule immediately, returning its job id.
	 * 
	 *  Deliberately does not move the schedule's high-water mark: testing a
	 *  schedule now must not cancel the occurrence it was created for.
	 */
	runScheduleNow: (id: string) => typedError<string, CommandError>(__TAURI_INVOKE("run_schedule_now", { id })),
	previewCron: (expression: string, timezone: ScheduleTimezone) => typedError<CronPreview, CommandError>(__TAURI_INVOKE("preview_cron", { expression, timezone })),
	/**
	 *  The `dbsync` invocation that runs this schedule from system cron.
	 * 
	 *  Offered because plenty of DBAs would rather their backups were driven by the
	 *  same cron that runs everything else on the box than by a desktop app that
	 *  has to stay open.
	 */
	crontabLine: (id: string) => typedError<string, CommandError>(__TAURI_INVOKE("crontab_line", { id })),
	schedulerStatus: () => typedError<SchedulerStatus, CommandError>(__TAURI_INVOKE("scheduler_status")),
	getAppSettings: () => typedError<AppSettings, CommandError>(__TAURI_INVOKE("get_app_settings")),
	setAppSettings: (next: AppSettings) => typedError<AppSettings, CommandError>(__TAURI_INVOKE("set_app_settings", { next })),
	/**  One page of configuration changes, newest first. */
	listAudit: (limit: number, offset: number) => typedError<AuditPage, CommandError>(__TAURI_INVOKE("list_audit", { limit, offset })),
	/**  Size and growth across the backup library. */
	libraryStats: (directory: string | null) => typedError<LibraryStats, CommandError>(__TAURI_INVOKE("library_stats", { directory })),
	/**
	 *  Write a shareable bundle to a file and return the path.
	 * 
	 *  A file rather than a string, for the same reason the backup key export is:
	 *  the thing the user then does with it is put it somewhere. Unlike the key,
	 *  this one carries no secret — but returning a path keeps both exports
	 *  working the same way, and the file is what gets committed or attached.
	 */
	exportConfigToFile: () => typedError<string, CommandError>(__TAURI_INVOKE("export_config_to_file")),
	/**  Read a bundle and report what it would change, without changing anything. */
	previewConfigImport: (path: string) => typedError<ConfigBundle_Serialize, CommandError>(__TAURI_INVOKE("preview_config_import", { path })),
	/**  Apply a bundle. Never writes a credential; never removes anything. */
	importConfig: (path: string) => typedError<ImportReport, CommandError>(__TAURI_INVOKE("import_config", { path })),
	listDestinations: () => typedError<DestinationView[], CommandError>(__TAURI_INVOKE("list_destinations")),
	/**
	 *  Create a destination and file its credential.
	 * 
	 *  The secret arrives here and goes straight to the keychain; it is never
	 *  stored in the database and never returned. This is the only direction a
	 *  secret is allowed to travel across this boundary.
	 */
	createDestination: (input: DestinationCreate, secretAccessKey: string) => typedError<DestinationView, CommandError>(__TAURI_INVOKE("create_destination", { input, secretAccessKey })),
	updateDestination: (id: string, patch: DestinationUpdate) => typedError<DestinationView, CommandError>(__TAURI_INVOKE("update_destination", { id, patch })),
	/**  Replace a destination's secret access key. */
	setDestinationCredential: (id: string, secretAccessKey: string) => typedError<DestinationView, CommandError>(__TAURI_INVOKE("set_destination_credential", { id, secretAccessKey })),
	/**  Delete a destination and the credential belonging to it. */
	deleteDestination: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_destination", { id })),
	/**
	 *  Check that a destination is reachable and its credential is accepted.
	 * 
	 *  Narrow on purpose, and the UI says so: this proves the endpoint resolves,
	 *  the credential is valid and the bucket can be listed. It does not prove the
	 *  credential can *write* — only a write proves that.
	 */
	testDestination: (id: string) => typedError<DestinationCheck, CommandError>(__TAURI_INVOKE("test_destination", { id })),
	/**
	 *  Upload an artifact that is already on disk to every enabled destination.
	 * 
	 *  For backfilling artifacts taken before a destination existed, and for
	 *  retrying one whose upload failed. Returns a job id immediately and follows
	 *  the same event stream as a backup, because an upload of a large artifact is
	 *  exactly as long-running as the dump that produced it.
	 * 
	 *  Deliberately writes no job-history row: history records what a *profile*
	 *  did, and a manual push has no profile behind it. Inventing one would put a
	 *  row in the list attributed to a connection that was not involved.
	 */
	pushArtifactOffsite: (path: string) => typedError<string, CommandError>(__TAURI_INVOKE("push_artifact_offsite", { path })),
	cliStatus: () => typedError<CliStatus, CommandError>(__TAURI_INVOKE("cli_status")),
	/**
	 *  Link the bundled `dbsync` somewhere a terminal will find it.
	 * 
	 *  Never escalates privileges. When nothing is writable the result carries the
	 *  exact command for the user to run instead — an app that asks for an
	 *  administrator password to write into a system directory is asking for more
	 *  trust than this feature is worth.
	 */
	installCli: () => typedError<CliInstall, CommandError>(__TAURI_INVOKE("install_cli")),
	/**
	 *  Look for every client binary through the configured source.
	 * 
	 *  On a blocking thread: probing versions runs each tool, and with a container
	 *  source that means starting a container per tool. Holding the async runtime
	 *  for that would freeze every other command, including the one drawing the
	 *  spinner the user is looking at.
	 */
	discoverTools: () => typedError<ToolStatus[], CommandError>(__TAURI_INVOKE("discover_tools")),
	/**
	 *  The same, for a source the user is considering but has not saved.
	 * 
	 *  Separate from [`discover_tools`] so the settings page can answer "would
	 *  this container work?" before committing to it — finding out by saving and
	 *  then watching a backup fail is a much worse way to learn.
	 */
	testToolSource: (source: ToolSource) => typedError<ToolStatus[], CommandError>(__TAURI_INVOKE("test_tool_source", { source })),
	/**  Running containers, for the exec source picker. */
	listDockerContainers: () => typedError<DockerContainer[], CommandError>(__TAURI_INVOKE("list_docker_containers")),
	/**
	 *  Install a client with Homebrew.
	 * 
	 *  The formula is validated in the engine against the app's own list, so this
	 *  cannot be talked into installing something else.
	 */
	installToolWithBrew: (formula: string) => typedError<string, CommandError>(__TAURI_INVOKE("install_tool_with_brew", { formula })),
};

/** Events */
export const events = {
	jobFinished: makeEvent<JobFinished>("job-finished"),
	jobProgress: makeEvent<JobProgress>("job-progress"),
	navigateTo: makeEvent<NavigateTo>("navigate-to"),
	scheduledRunFinished: makeEvent<ScheduledRunFinished>("scheduled-run-finished"),
};

/* Types */
export type AppInfo = {
	engine_version: string,
	store_path: string,
};

export type AppSettings = {
	/**
	 *  Whether the app runs schedules itself.
	 * 
	 *  On by default: someone who creates a schedule in the app expects the app
	 *  to run it. Turning it off is for people driving schedules from system
	 *  cron who do not want two copies firing.
	 */
	scheduler_enabled: boolean,
	/**
	 *  Whether closing the window leaves the app running in the tray.
	 * 
	 *  On by default, because with it off a closed window silently stops every
	 *  schedule — the app would appear to be configured for nightly backups
	 *  that never happen.
	 */
	close_to_tray: boolean,
	/**
	 *  Launch at login. Read from the OS rather than from the store, since the
	 *  user can change it outside the app.
	 */
	launch_at_login: boolean,
	/**
	 *  Whether the user has already been told that closing the window does not
	 *  quit. Shown once, not every time.
	 */
	background_notice_shown: boolean,
	/**
	 *  Where the external client binaries come from.
	 * 
	 *  A property of this machine rather than of any one database, which is
	 *  why it lives here and not on a profile. A per-profile binary override
	 *  still wins over it.
	 */
	tool_source: ToolSource,
};

/**  One artifact, as the library lists it. */
export type Artifact = {
	path: string,
	filename: string,
	size_bytes: number | null,
	modified_at: string,
	/**  Populated when a readable manifest sits beside the artifact. */
	database: string | null,
	engine: Engine | null,
	source_profile_name: string | null,
	table_count: number | null,
	tables_with_data: number | null,
	/**
	 *  What kind of artifact this is.
	 * 
	 *  The UI needs it to know whether part of the artifact can be restored on
	 *  its own: a `pg_dump` archive can, a flat `.sql.gz` stream cannot, and
	 *  offering the choice on one that cannot is worse than not offering it.
	 */
	format: ArtifactFormat | null,
	/**
	 *  Every table in the artifact.
	 * 
	 *  The universe a table set is completed against at restore time — the
	 *  artifact is what can come back, not whatever the destination happens to
	 *  hold now.
	 */
	tables: string[],
	/**
	 *  Which connection this was taken from.
	 * 
	 *  A table set belongs to the *source* profile, but a restore picks a
	 *  destination. Offering the destination's sets would offer sets written
	 *  against a different schema.
	 */
	source_profile_id: string | null,
	/**  `None` when there is no manifest to check against. */
	has_manifest: boolean,
};

export type ArtifactFormat = 
/**  Single gzipped SQL stream (MySQL, and PostgreSQL `plain` format). */
"sql_gz" | 
/**  `pg_dump -Fc` custom archive. Supports selective and parallel restore. */
"pg_custom" | 
/**  `pg_dump -Fd` directory archive. Supports parallel dump and restore. */
"pg_directory" | 
/**  `mydumper` output directory. */
"mydumper_dir" | 
/**
 *  `mongodump --archive --gzip`. A single self-describing stream holding
 *  every selected collection, which is what makes MongoDB fit the artifact
 *  model the rest of this application is built on: one file the client
 *  produced, whose checksum it controls.
 * 
 *  `--gzip` compresses *inside* the archive rather than wrapping it, so
 *  [`crate::backup::CommonBackupOptions::compress`] is honoured by the tool
 *  and no second gzip layer is added.
 */
"mongo_archive";

/**  Where a restore step gets the artifact it replays. */
export type ArtifactSource = 
/**  Whatever the most recent backup step in this pipeline wrote. */
{ from: "previous_step" } | 
/**  The newest artifact in a directory, the way a drill picks one. */
{ from: "newest_in_directory"; dir: string } | 
/**  One named file. */
{ from: "path"; path: string };

/**  One recorded change. */
export type AuditEntry = {
	id: string,
	at: string,
	/**  Machine-readable verb, e.g. `profile.deleted`. */
	action: string,
	/**  What it happened to, in words a person recognises. */
	subject: string,
	detail: string,
};

/**
 *  One page of recorded changes, with the size of the whole set.
 * 
 *  The count travels with the rows for the same reason as [`crate::job::JobPage`]:
 *  fetched separately it can disagree with the page it is describing.
 */
export type AuditPage = {
	entries: AuditEntry[],
	/**  Total rows in `audit_log`, not the length of `entries`. */
	total: number,
};

export type BackupRequest = {
	common: CommonBackupOptions,
	engine: EngineBackupOptions,
};

export type CliInstall = {
	path: string,
	/**
	 *  False when the directory is not on the user's `PATH`, so the UI can say
	 *  what still has to be done rather than claiming success.
	 */
	on_path: boolean,
	/**  Set when nothing could be written and the user has to do it themselves. */
	manual_command: string | null,
};

/**  Where the CLI is, and whether a terminal can already find it. */
export type CliStatus = {
	/**  The copy shipped inside this application bundle, if it is there. */
	bundled_path: string | null,
	/**  An existing `dbsync` already on `PATH`, if any. */
	installed_path: string | null,
	/**  True when the thing on `PATH` is the copy this app ships. */
	linked_to_bundle: boolean,
	/**  Directories this app could write a link into, best first. */
	install_targets: string[],
};

/**
 *  Error shape crossing into the webview.
 * 
 *  Carries a human-readable message and a machine-readable kind so the UI can
 *  react (e.g. highlight a duplicate name field) without string matching.
 */
export type CommandError = {
	kind: string,
	message: string,
};

export type CommonBackupOptions = {
	database: string,
	selections: TableSelection[],
	output_dir: string,
	/**  Gzip the stream. Ignored for formats that compress internally. */
	compress: boolean,
	/**
	 *  Encrypt at rest with age. Wired in a later milestone; the manifest
	 *  already records the flag.
	 */
	encrypt: boolean,
	/**
	 *  Count the rows of each data table before dumping, and record the
	 *  numbers in the manifest.
	 * 
	 *  # What it buys and what it costs
	 * 
	 *  A restore drill checks an artifact against its own manifest. Without
	 *  these numbers the manifest only says which tables were *selected* for
	 *  data, so a table that comes back empty cannot be told apart from one
	 *  that was empty at the source, and the drill has to record it as
	 *  not compared. With them the drill compares exactly, and a dump that
	 *  lost rows is caught.
	 * 
	 *  The cost is an exact `COUNT(*)` per data table — a full scan, on top of
	 *  the scan the dump itself does. That is why it is a choice.
	 *  [`crate::db::TableInfo::estimated_rows`] is not usable here: the planner
	 *  estimate reads zero for tables that plainly have rows, which is the
	 *  exact failure this project replaced in the Bash tool.
	 * 
	 *  Defaulted to off on deserialise so a schedule stored before this
	 *  existed does not silently acquire the cost, matching `deep_verify`.
	 */
	record_row_counts?: boolean,
};

export type ConfigBundle = ConfigBundle_Serialize | ConfigBundle_Deserialize;

export type ConfigBundle_Deserialize = {
	bundle_version: number,
	exported_at: string,
	/**  The version of DBSync that wrote it, for a human reading a diff. */
	engine_version: string,
	/**  Defaulted rather than required, so a version 1 bundle still parses. */
	ssh_connections?: SharedSshConnection[],
	profiles: SharedProfile_Deserialize[],
	plans: SharedPlan[],
	destinations: SharedDestination[],
};

export type ConfigBundle_Serialize = {
	bundle_version: number,
	exported_at: string,
	/**  The version of DBSync that wrote it, for a human reading a diff. */
	engine_version: string,
	/**  Defaulted rather than required, so a version 1 bundle still parses. */
	ssh_connections: SharedSshConnection[],
	profiles: SharedProfile_Serialize[],
	plans: SharedPlan[],
	destinations: SharedDestination[],
};

export type ConnectionProfile = {
	id: string,
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**
	 *  The saved SSH connection this profile tunnels through. `None` means
	 *  connect directly, without a tunnel.
	 */
	ssh_connection_id: string | null,
	db: DbConfig,
	tool_overrides: ToolOverrides,
	created_at: string,
	updated_at: string,
};

/**  Step-by-step result of testing a profile. */
export type ConnectionReport = {
	ssh: StepOutcome,
	tunnel: StepOutcome,
	db_ping: StepOutcome,
	catalog_read: StepOutcome,
	server_version: string | null,
	/**
	 *  Present when the connection stopped on an unverified host key. The UI
	 *  shows the fingerprint and, if the user accepts, pins it and retries.
	 */
	host_key_prompt: HostKeyPrompt | null,
};

/**
 *  What a cron expression means, and the next few times it fires.
 * 
 *  This is what the schedule form shows as the user types. Seeing the next five
 *  real timestamps is the only reliable way to catch a mistyped expression
 *  before it silently backs up at the wrong time for a month.
 */
export type CronPreview = {
	description: string,
	next_runs: string[],
};

export type DatabaseInfo = {
	name: string,
	charset: string | null,
	collation: string | null,
};

/**  What the library holds for one database. */
export type DatabaseStats = {
	database: string,
	engine: Engine | null,
	artifacts: number | null,
	total_bytes: number | null,
	newest_bytes: number | null,
	newest_at: string,
	oldest_at: string,
	/**  Oldest first, so a chart reads left to right. */
	series: SizePoint[],
	/**
	 *  Average change per day across the whole span.
	 * 
	 *  `None` with fewer than two artifacts, or when they share a timestamp —
	 *  there is no rate to report, and inventing one from a single point is
	 *  the kind of number that gets quoted back later as if it meant
	 *  something.
	 */
	bytes_per_day: number | null,
	shrinks: ShrinkWarning[],
};

/**
 *  Database coordinates *as seen from the SSH host* (or from this machine when
 *  `ConnectionProfile::ssh_connection_id` is `None`).
 */
export type DbConfig = {
	host: string,
	port: number,
	user: string,
	database: string | null,
};

export type Destination = {
	id: string,
	name: string,
	kind: DestinationKind,
	/**
	 *  Disabled destinations are skipped by every backup but keep their
	 *  configuration and their credential, so turning one off for an
	 *  afternoon does not mean setting it up again.
	 */
	enabled: boolean,
	/**
	 *  Retention applied to the objects *at this destination*.
	 * 
	 *  Separate from the local policy on purpose. Off-site storage is usually
	 *  cheaper and is the copy that survives losing the machine, so keeping
	 *  more there than locally is the common case — a single shared policy
	 *  would force the two to move together.
	 */
	retention: RetentionPolicy,
	created_at: string,
	updated_at: string,
};

/**
 *  What a reachability check found.
 * 
 *  A struct rather than a `Result` across the boundary, because "this one is
 *  broken" is information the page shows rather than an error that stops it.
 */
export type DestinationCheck = {
	ok: boolean,
	detail: string,
};

/**  What the caller supplies to create one. The secret is handled separately. */
export type DestinationCreate = {
	name: string,
	kind: DestinationKind,
	enabled?: boolean,
	retention?: RetentionPolicy,
};

/**
 *  The transports a destination can use.
 * 
 *  A tagged enum rather than a bare struct because the persisted form is JSON
 *  in a single column: adding SFTP or a second object-store dialect later is a
 *  new variant, not a migration.
 */
export type DestinationKind = 
/**
 *  Anything speaking the S3 API: AWS, Cloudflare R2, Backblaze B2,
 *  Wasabi, MinIO.
 */
{
	kind: "s3",
} & S3Destination;

/**  A partial edit. `None` leaves a field alone. */
export type DestinationUpdate = {
	name: string | null,
	kind: DestinationKind | null,
	enabled: boolean | null,
	retention: RetentionPolicy | null,
};

/**
 *  A destination as the UI sees it.
 * 
 *  The destination itself carries no secret — see [`db_sync_engine::destination`]
 *  — so it crosses the boundary whole. What is added here is the one fact the
 *  UI needs and cannot derive: whether a credential has been filed for it. A
 *  destination with no key is configured and unusable, which looks identical
 *  to a working one in every other respect.
 */
export type DestinationView = {
	has_credential: boolean,
	/**  Where this points, e.g. `s3://backups/prod`. */
	location: string,
} & Destination;

/**  A container that is currently running, for the exec source picker. */
export type DockerContainer = {
	name: string,
	image: string,
};

/**
 *  A supported database engine.
 * 
 *  The serde representation is snake_case and is the *single* source of truth
 *  for how these values are written to SQLite and to JSON manifests. Do not
 *  hand-write match arms mapping these to strings — use `Display`/`FromStr`.
 */
export type Engine = "mysql" | "postgres" | "mongo";

export type EngineBackupOptions = {
	engine: "mysql",
} & MysqlBackupOptions | {
	engine: "postgres",
} & PostgresBackupOptions | {
	engine: "mongo",
} & MongoBackupOptions;

export type EngineRestoreOptions = {
	engine: "mysql",
} & MysqlRestoreOptions | {
	engine: "postgres",
} & PostgresRestoreOptions | {
	engine: "mongo",
} & MongoRestoreOptions;

/**
 *  Environment classification for a connection profile.
 * 
 *  Drives colour-coding in the UI and the strictness of destructive-action
 *  confirmations — production targets require typed confirmation.
 */
export type EnvironmentTag = "prod" | "staging" | "dev";

/**  An unverified host key the user must decide about. */
export type HostKeyPrompt = {
	host_port: string,
	algorithm: string,
	fingerprint: string,
	/**
	 *  True when a *different* key was previously pinned. Far more serious
	 *  than first contact: it is what a machine-in-the-middle looks like.
	 */
	changed: boolean,
	/**  The fingerprint we had pinned, when `changed`. */
	previous_fingerprint: string | null,
};

/**  What an import changed, and what it deliberately did not. */
export type ImportReport = {
	ssh_connections_created: string[],
	ssh_connections_updated: string[],
	profiles_created: string[],
	profiles_updated: string[],
	plans_created: string[],
	plans_updated: string[],
	destinations_created: string[],
	destinations_updated: string[],
	/**
	 *  SSH connections whose key needs a passphrase that is not in this
	 *  machine's keychain. Named individually for the same reason connections
	 *  needing a password are: a count is not something anyone acts on.
	 */
	ssh_needing_passphrase: string[],
	/**
	 *  Connections that now exist but cannot connect until someone supplies a
	 *  password. Named individually, because "some of these need credentials"
	 *  is not something anyone acts on.
	 */
	needs_credentials: string[],
	/**  Plans whose profile was not in the bundle and is not on this machine. */
	orphaned_plans: string[],
	/**
	 *  Connections that named an SSH connection the bundle did not carry.
	 *  They are imported as direct connections and listed here, because a
	 *  tunnelled profile silently becoming a direct one is exactly the kind
	 *  of change that is only noticed when it fails.
	 */
	orphaned_ssh_references: string[],
	/**  Destinations that exist but have no stored access key. */
	destinations_needing_keys: string[],
};

export type InertRule = {
	rule: MaskRule,
	reason: string,
};

/**  Result of checking an artifact against its manifest. */
export type IntegrityCheck = { status: "ok" } | { status: "mismatch"; expected: string; actual: string } | { status: "no_manifest" } | { status: "unreadable"; detail: string };

/**
 *  Emitted when a job reaches a terminal state, so the UI can refresh history
 *  without polling.
 */
export type JobFinished = {
	job_id: string,
	outcome: string,
};

export type JobKind = "backup" | "restore" | "verify" | "sync";

export type JobOutcome = "success" | "failed" | "cancelled";

/**
 *  One page of job history, with the size of the whole set.
 * 
 *  The count travels with the rows rather than in a second command: a job can
 *  finish between two calls, and a pager that reads "page 9 of 8" because the
 *  total was fetched separately is worse than no pager.
 */
export type JobPage = {
	jobs: JobRecord[],
	/**  Total rows in `job_history`, not the length of `jobs`. */
	total: number,
};

export type JobPhase = "initializing" | "ssh_connect" | "tunneling" | "introspect" | "dump_schema" | "dump_data" | "compress" | "transfer" | "restore" | "verify" | "cleanup" | "done";

/**  One progress record from a running job. */
export type JobProgress = ProgressEvent;

/**  The persisted record of one job run. */
export type JobRecord = {
	id: string,
	kind: JobKind,
	source_profile_id: string,
	dest_profile_id: string | null,
	started_at: string,
	finished_at: string | null,
	outcome: JobOutcome | null,
	artifact_path: string | null,
	/**
	 *  Serialised options, kept opaque so option shapes can evolve without a
	 *  schema migration.
	 */
	options_json: string,
	/**
	 *  Durable log. Accumulated from the event stream by [`JobContext`] — the
	 *  broadcast channel is lossy and must never be the only record.
	 */
	log: string,
};

/**  One planned or completed step of a job. */
export type JobStep = {
	job_id: string,
	/**  1-based, because it is read as "step 2 of 5". */
	index: number,
	kind: JobStepKind,
	/**
	 *  Human label decided when the step was planned, so it can name the
	 *  actual database or destination rather than repeating the kind.
	 */
	label: string,
	/**  `None` while the step is still pending. */
	started_at: string | null,
	finished_at: string | null,
	/**  `None` means pending if `started_at` is also none, running otherwise. */
	outcome: JobStepOutcome | null,
	detail: JobStepDetail,
};

/**
 *  What one step produced, in the few terms worth showing next to it.
 * 
 *  Every field is optional and defaulted. It is stored in an opaque JSON
 *  column, so a field added later still reads back against rows written before
 *  it existed — and a blob that cannot be parsed at all degrades to this
 *  default rather than making the job page fail to load.
 * 
 *  No `skip_serializing_if`, deliberately. It would make the serialised and
 *  deserialised shapes differ, and specta answers that by exporting two
 *  TypeScript types with a union over them — so the page consuming this would
 *  name `JobStep_Serialize`. A few null fields in a tiny blob is the cheaper
 *  side of that trade.
 */
export type JobStepDetail = {
	/**  Path of the artifact this step wrote or read. */
	artifact?: string | null,
	/**  Database this step wrote to. */
	database?: string | null,
	tables_checked?: number | null,
	/**  Why this step failed, as it was reported to the user. */
	error?: string | null,
	/**
	 *  Anything else worth one line — "3 artifacts removed", "2 of 2 copies
	 *  pushed", "verification found 1 mismatch".
	 */
	notes?: string[],
};

/**  What a step does. A closed set, so the UI can label every one it meets. */
export type JobStepKind = "backup" | "restore" | "verify" | "mask" | "offsite" | "retention" | "drill" | "cleanup";

/**
 *  How a step ended.
 * 
 *  Distinct from [`crate::job::JobOutcome`] because of `Skipped`, which is the
 *  whole reason these rows are planned up front: a step the run never reached
 *  is not a success, not a failure, and not still running.
 */
export type JobStepOutcome = "success" | "failed" | "skipped" | "cancelled";

/**
 *  What the UI is allowed to know about the backup key.
 * 
 *  The secret half never appears here — [`export`] is the only way out, and it
 *  is a deliberate, separate action.
 */
export type KeyStatus = {
	exists: boolean,
	/**  `age1...`, safe to display. */
	public: string | null,
	exported: boolean,
	extra_recipients: string[],
};

/**  Everything the library page reports. */
export type LibraryStats = {
	total_artifacts: number | null,
	total_bytes: number | null,
	/**
	 *  Artifacts with no readable manifest, so no database to group under.
	 * 
	 *  Reported rather than dropped: they still take up space, and a library
	 *  whose totals silently exclude them would understate what is on disk.
	 */
	unattributed: number | null,
	unattributed_bytes: number | null,
	/**  Largest total first — the one filling the disk is the one to look at. */
	databases: DatabaseStats[],
};

export type LogLevel = "debug" | "info" | "warn" | "error";

/**  One column, one transform. */
export type MaskRule = {
	/**
	 *  Table name as the plan spells it. For PostgreSQL this may be
	 *  `schema.table`; a bare name means `public`.
	 */
	table: string,
	column: string,
	transform: MaskTransform,
};

/**  What to replace a column's values with. */
export type MaskTransform = 
/**  Salted SHA-256, hex, optionally truncated. NULL stays NULL. */
{ kind: "hash"; length: number | null } | 
/**  A deterministic address at [`FAKE_EMAIL_DOMAIN`]. NULL stays NULL. */
{ kind: "email" } | 
/**  A deterministic number in the reserved 555 range. NULL stays NULL. */
{ kind: "phone" } | 
/**  Every row set to NULL. Fails loudly on a NOT NULL column. */
{ kind: "null" } | 
/**
 *  Every row set to one literal, NULLs included.
 * 
 *  Bound as text, so this is for text-ish columns. On a numeric column
 *  PostgreSQL rejects it outright and MySQL coerces; either way the
 *  post-mask check has the final say.
 */
{ kind: "constant"; value: string };

/**  The SQL a masking run would send to the destination. */
export type MaskingPreview = {
	/**  One `UPDATE` per table. */
	updates: string[],
	/**  The read-back; every count must be zero or the sync aborts. */
	checks: string[],
	/**  Rules that would not run, with the reason. */
	inert: InertRule[],
};

/**
 *  Derived rather than written out, unlike the other two engines': every
 *  default here really is the type's own. The reasoning that matters — why
 *  `oplog` is off — belongs on the field, not in a hand-written `impl` that
 *  restates `false`.
 */
export type MongoBackupOptions = {
	/**
	 *  Capture the oplog during the dump so the restore can replay to a single
	 *  point in time.
	 * 
	 *  This is MongoDB's answer to `--single-transaction`, and the reason it is
	 *  **off** by default is that it is not equivalent: `--oplog` requires a
	 *  replica set and fails outright on a standalone server, which is what
	 *  most development databases are. Defaulting it on would make the common
	 *  case an error.
	 * 
	 *  Without it, a dump of a database being written to is consistent within
	 *  each collection and not across them. That is a real caveat and the UI
	 *  says so rather than burying it here.
	 */
	oplog: boolean,
	/**
	 *  Collections dumped at once. `None` leaves `mongodump` to its own
	 *  default.
	 */
	parallel_collections: number | null,
	/**
	 *  Also dump the users and roles defined on this database.
	 * 
	 *  The counterpart of PostgreSQL's `include_globals`, and off for the same
	 *  reason: restoring them into another server changes who can log in there.
	 */
	dump_users_and_roles: boolean,
	extra_flags: string[],
};

export type MongoRestoreOptions = {
	/**
	 *  Drop each collection before restoring it.
	 * 
	 *  Distinct from [`TargetNaming::DropAndRecreate`], which drops the whole
	 *  database: this is what makes `IntoExisting` replace rather than merge.
	 *  Off by default, so the safe reading of "restore into this database" is
	 *  the one that happens without asking.
	 */
	drop_collections: boolean,
	/**
	 *  Restore only these collections. Uses `--nsInclude`, so it needs the
	 *  archive format — which every MongoDB artifact this app writes is.
	 */
	only_collections: string[],
	/**  Collections restored at once, and insertion workers within each. */
	parallel_collections: number | null,
	insertion_workers: number | null,
	/**
	 *  Stop at the first failed document rather than carrying on.
	 * 
	 *  On by default, and the default is the point: `mongorestore` otherwise
	 *  reports failures on stderr, exits 0, and leaves a database that is
	 *  missing documents nobody was told about. A restore that half-worked has
	 *  to be a failed restore, or the drill is checking a lie.
	 */
	stop_on_error: boolean,
	/**  Rebuild indexes after the documents land. */
	restore_indexes: boolean,
	/**
	 *  Skip the destination's schema validators.
	 * 
	 *  Off by default: a validator rejecting a document is information, not an
	 *  obstacle. It matters most after masking, where a masked value can stop
	 *  matching a pattern the source enforced.
	 */
	bypass_document_validation: boolean,
};

export type MysqlBackupOptions = {
	/**  Consistent snapshot without locking. Only meaningful for InnoDB. */
	single_transaction: boolean,
	/**  Emit binary columns as hex. Without this, BLOBs can corrupt in transit. */
	hex_blob: boolean,
	set_gtid_purged_off: boolean,
	add_drop_table: boolean,
	extended_insert: boolean,
	routines: boolean,
	triggers: boolean,
	events: boolean,
	default_character_set: string,
	/**
	 *  Send `--column-statistics=0`, required when an 8.x client talks to a
	 *  pre-8.0 server.
	 */
	disable_column_statistics: boolean,
	/**  Strip `DEFINER=` clauses so restores need no SUPER privilege. */
	strip_definer: boolean,
	/**  Use mydumper for a parallel dump when the binary is available. */
	parallel_threads: number | null,
	extra_flags: string[],
};

export type MysqlRestoreOptions = {
	foreign_key_checks_off: boolean,
	unique_checks_off: boolean,
	autocommit_off: boolean,
	/**  Skip writing the restore to the destination's binary log. */
	disable_binlog: boolean,
	charset: string,
	collation: string,
};

/**
 *  The tray asking the open window to show a particular page.
 * 
 *  An event rather than a navigation, so a window that is already showing live
 *  job progress does not get reloaded out from under the user.
 */
export type NavigateTo = string;

/**  When to raise a notification for a scheduled run. */
export type NotifyPolicy = "never" | 
/**
 *  The default. A nightly backup that worked is not news; one that failed
 *  is the only thing the user needs to see.
 */
"on_failure" | "always";

export type PgDumpFormat = 
/**
 *  `-Fc`. Default: the only format supporting both selective and parallel
 *  restore.
 */
"custom" | 
/**  `-Fd`. Adds parallel *dump*. */
"directory" | 
/**  `-Fp`. Plain SQL; no selective restore. */
"plain";

/**  A saved chain of actions. */
export type Pipeline = {
	id: string,
	name: string,
	steps: PipelineStep[],
	/**
	 *  The destructive signature a human typed back when arming this pipeline
	 *  for unattended use, or `None` if it has never been armed.
	 * 
	 *  Compared against the current signature rather than trusted: see
	 *  [`Pipeline::is_armed`].
	 */
	unattended_ack?: string | null,
	created_at: string,
	updated_at: string,
};

export type PipelineCreate = {
	name: string,
	steps: PipelineStep[],
};

/**
 *  One action in a pipeline.
 * 
 *  Internally tagged, so a step gains a field without invalidating the stored
 *  JSON of every pipeline written before it. Every added field is
 *  `#[serde(default)]` for the same reason, and because an unattended run must
 *  not acquire a new cost on upgrade.
 */
export type PipelineStep = { kind: "backup"; profile_id: string; database: string; 
/**
 *  A saved table set. When set, its selections are used and
 *  `selections` is ignored — the set is the thing being maintained.
 */
plan_id?: string | null; selections?: TableSelection[]; 
/**  Defaults to the app's backup directory when absent. */
output_dir?: string | null; compress?: boolean; encrypt?: boolean; record_row_counts?: boolean; engine: EngineBackupOptions } | { kind: "restore"; profile_id: string; source?: ArtifactSource; naming: TargetNaming; engine: EngineRestoreOptions; verify_checksum?: boolean } | 
/**  Compare the restored database against the source it came from. */
{ kind: "verify"; deep?: boolean } | 
/**  Mask columns on the database the previous restore wrote. */
{ kind: "mask"; rules?: MaskRule[] } | 
/**  Copy the artifact to every enabled off-site destination. */
{ kind: "push_offsite" } | 
/**  Prune the backup directory the artifact was written to. */
{ kind: "retention"; policy: RetentionPolicy } | 
/**
 *  Prove the newest artifact restores, into a scratch database that is
 *  dropped afterwards.
 */
{ kind: "drill"; profile_id: string; artifact_dir?: string | null; deep?: boolean; keep_on_failure?: boolean };

export type PipelineUpdate = {
	name?: string | null,
	steps?: PipelineStep[] | null,
};

export type PostgresBackupOptions = {
	format: PgDumpFormat,
	no_owner: boolean,
	no_privileges: boolean,
	blobs: boolean,
	/**  Restrict to these schemas; empty means all. */
	schemas: string[],
	serializable_deferrable: boolean,
	/**  Parallel dump jobs. Only honoured for `Directory`. */
	parallel_jobs: number | null,
	/**  Additionally dump roles/globals via `pg_dumpall --globals-only`. */
	include_globals: boolean,
	extra_flags: string[],
};

export type PostgresRestoreOptions = {
	no_owner: boolean,
	no_privileges: boolean,
	/**  `pg_restore -j`. Only valid for archive formats. */
	parallel_jobs: number | null,
	/**  Restore only these tables. Requires an archive format. */
	only_tables: string[],
	clean: boolean,
};

export type ProfileCreate = {
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	ssh_connection_id?: string | null,
	db: DbConfig,
	tool_overrides?: ToolOverrides,
};

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh_connection_id` is doubly-optional on purpose, and the distinction is
 *  carried by *presence*, not by value: omitting the key leaves the tunnel
 *  alone, while sending an explicit `null` detaches it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate = ProfileUpdate_Serialize | ProfileUpdate_Deserialize;

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh_connection_id` is doubly-optional on purpose, and the distinction is
 *  carried by *presence*, not by value: omitting the key leaves the tunnel
 *  alone, while sending an explicit `null` detaches it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate_Deserialize = {
	name?: string | null,
	engine?: Engine | null,
	environment?: EnvironmentTag | null,
	ssh_connection_id?: string | null,
	db?: DbConfig | null,
	tool_overrides?: ToolOverrides | null,
};

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh_connection_id` is doubly-optional on purpose, and the distinction is
 *  carried by *presence*, not by value: omitting the key leaves the tunnel
 *  alone, while sending an explicit `null` detaches it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate_Serialize = {
	name: string | null,
	engine: Engine | null,
	environment: EnvironmentTag | null,
	ssh_connection_id?: string | null,
	db: DbConfig | null,
	tool_overrides: ToolOverrides | null,
};

/**
 *  A single point-in-time progress record.
 * 
 *  Every field beyond `job_id`/`ts`/`phase`/`level`/`message` is optional
 *  because different phases have different meaningful measurements: a schema
 *  dump reports bytes, a data dump reports per-table counts.
 */
export type ProgressEvent = {
	job_id: string,
	ts: string,
	phase: JobPhase,
	level: LogLevel,
	message: string,
	table: string | null,
	done: number | null,
	total: number | null,
	/**  What `done`/`total` count. `None` whenever they are. */
	unit: ProgressUnit | null,
	/**
	 *  Size of the artifact written so far.
	 * 
	 *  Separate from `done` because the two answer different questions during
	 *  the same phase: a MySQL dump knows which table it is on *and* how large
	 *  the file has grown, and neither one implies the other.
	 */
	bytes: number | null,
	rows: number | null,
	percent: number | null,
	/**
	 *  Which step of a composite job produced this, 1-based.
	 * 
	 *  Never set at a call site. [`crate::job::JobContext`] stamps it from the
	 *  step it is currently inside, so a single-step job leaves it `None` and
	 *  the fifty places that build an event stay unaware that steps exist.
	 */
	step: number | null,
	step_total: number | null,
};

/**
 *  What the `done`/`total` pair on a [`ProgressEvent`] counts.
 * 
 *  Carried explicitly because the two are not interchangeable to a reader:
 *  "table 12 of 47" and "3 MB of 10 MB" are the same numbers with different
 *  meanings. It also decides whether an estimate is worth showing at all —
 *  bytes advance at a roughly steady rate, table counts do not, because table
 *  sizes differ by orders of magnitude within one database.
 */
export type ProgressUnit = "bytes" | "tables";

export type RestoreRequest = {
	artifact_path: string,
	naming: TargetNaming,
	engine: EngineRestoreOptions,
	/**  Verify the artifact checksum before touching the destination. */
	verify_checksum: boolean,
	/**  Typed confirmation supplied by the user for a destructive restore. */
	typed_confirmation: string | null,
};

export type RetentionPolicy = {
	/**  Keep at most this many of the most recent artifacts. */
	keep_last: number | null,
	/**  Delete artifacts older than this many days. */
	max_age_days: number | null,
};

/**  What happened on one scheduled run. */
export type RunReport = {
	/**  Always `"dbsync.run.finished"`, so a receiving endpoint can route on it. */
	event: string,
	schedule_id: string,
	schedule_name: string,
	job_id: string,
	kind: JobKind,
	outcome: JobOutcome,
	/**
	 *  The occurrence this run was for, which is not the same as when it
	 *  started if the tick was late or it was a catch-up run.
	 */
	scheduled_for: string,
	started_at: string,
	finished_at: string,
	duration_seconds: number | null,
	/**  Profile *name*. Never the host, port, user or password. */
	source_profile: string,
	dest_profile: string | null,
	database: string,
	target_database: string | null,
	/**  File name only — never the directory. See the module docs. */
	artifact_name: string | null,
	artifact_bytes: number | null,
	verification: VerificationSummary | null,
	removed_artifacts: number | null,
	error: string | null,
};

/**  An S3-compatible bucket. No secret: see the module docs. */
export type S3Destination = {
	/**  Base URL with scheme, e.g. `https://s3.eu-west-1.amazonaws.com`. */
	endpoint: string,
	region: string,
	bucket: string,
	/**  Key prefix, so one bucket can hold several sources. */
	prefix?: string,
	/**  `https://endpoint/bucket/key` rather than `https://bucket.endpoint/key`. */
	path_style?: boolean,
	access_key_id: string,
};

/**  A named, recurring job. */
export type Schedule = {
	id: string,
	name: string,
	/**
	 *  Defaulted, so every schedule written before drills existed reads as the
	 *  sync it has always been.
	 */
	kind?: ScheduleKind,
	/**
	 *  The plan supplies the source profile, database and table selection.
	 * 
	 *  Required for a sync and always absent for a drill, which restores
	 *  whatever artifact is newest rather than selecting anything.
	 */
	plan_id: string | null,
	/**
	 *  For a sync, `None` makes this a backup-only schedule. For a drill this
	 *  is the connection being drilled, and it is required.
	 * 
	 *  Deliberately not a foreign key. If the destination profile is deleted,
	 *  the schedule must fail loudly at its next run rather than have the
	 *  column quietly set to NULL — which would silently downgrade a
	 *  replication job to a local backup and nobody would notice for months.
	 */
	dest_profile_id: string | null,
	/**
	 *  The chain this schedule runs. Required for a pipeline schedule and
	 *  always absent otherwise.
	 * 
	 *  Deliberately not a foreign key, for the same reason `dest_profile_id`
	 *  is not: a deleted pipeline has to make the next run fail loudly rather
	 *  than leave a schedule that still looks configured and quietly does
	 *  nothing.
	 */
	pipeline_id?: string | null,
	cron: string,
	timezone: ScheduleTimezone,
	enabled: boolean,
	action: ScheduleAction,
	webhook_url: string | null,
	notify: NotifyPolicy,
	/**
	 *  Run an occurrence that was missed while the machine was asleep or the
	 *  app was closed. At most one make-up run, however many were missed.
	 */
	catch_up: boolean,
	last_run_at: string | null,
	last_outcome: JobOutcome | null,
	last_job_id: string | null,
	created_at: string,
	updated_at: string,
};

/**  Everything a scheduled run does, beyond what the plan already says. */
export type ScheduleAction = {
	output_dir: string,
	compress: boolean,
	encrypt: boolean,
	backup: EngineBackupOptions,
	/**  Present exactly when the schedule has a destination profile. */
	restore: ScheduleRestore | null,
	verify: boolean,
	/**
	 *  Compare table contents, not only row counts.
	 * 
	 *  Off by default and defaulted on deserialise: it costs a full scan of
	 *  every table on both sides, and an existing schedule must not silently
	 *  acquire that cost on upgrade.
	 */
	deep_verify?: boolean,
	retention: RetentionPolicy | null,
	/**
	 *  Count rows before dumping, so a drill can compare exactly.
	 * 
	 *  See [`crate::backup::CommonBackupOptions::record_row_counts`]. Defaulted
	 *  off so an existing schedule does not silently acquire the scan.
	 */
	record_row_counts?: boolean,
	/**
	 *  Drills only: leave the scratch database behind when the drill fails, so
	 *  the wreckage can be inspected in the morning.
	 * 
	 *  A drill that *passes* always cleans up, whatever this says.
	 */
	keep_on_failure?: boolean,
};

export type ScheduleCreate = {
	name: string,
	kind?: ScheduleKind,
	plan_id: string | null,
	dest_profile_id: string | null,
	pipeline_id?: string | null,
	cron: string,
	timezone?: ScheduleTimezone,
	action: ScheduleAction,
	webhook_url: string | null,
	notify?: NotifyPolicy,
	catch_up?: boolean,
	enabled?: boolean,
};

/**
 *  What a schedule does when it fires.
 * 
 *  The two kinds answer different questions. A sync asks "is today's data
 *  somewhere else"; a drill asks "does the thing we have actually restore".
 *  Only the second one can tell you your backups are worth having, and it is
 *  the one nobody remembers to run by hand — which is the whole argument for
 *  it being schedulable.
 */
export type ScheduleKind = 
/**
 *  Back up a plan's tables, and optionally restore them to a destination.
 * 
 *  The default, and what every schedule written before drills existed is.
 */
"sync" | 
/**  Restore the newest artifact into a scratch database, check it, drop it. */
"drill" | 
/**
 *  Run a saved chain of actions.
 * 
 *  The only kind that may destroy a database unattended, and only while the
 *  pipeline is armed. See [`ScheduleError::PipelineNotArmed`].
 */
"pipeline";

/**  The restore half of a scheduled sync. */
export type ScheduleRestore = {
	naming: TargetNaming,
	options: EngineRestoreOptions,
};

/**  Which clock a cron expression is read against. */
export type ScheduleTimezone = 
/**
 *  The machine's local time. What "back up at 2am" normally means, at the
 *  cost of the daylight-saving behaviour described in the module docs.
 */
"local" | 
/**
 *  UTC. Immune to daylight saving; the right choice for a schedule that
 *  must fire exactly once every 24 hours.
 */
"utc";

/**  A partial update. Absent fields are left as they are. */
export type ScheduleUpdate = ScheduleUpdate_Serialize | ScheduleUpdate_Deserialize;

/**  A partial update. Absent fields are left as they are. */
export type ScheduleUpdate_Deserialize = {
	name: string | null,
	cron: string | null,
	timezone: ScheduleTimezone | null,
	enabled: boolean | null,
	action: ScheduleAction | null,
	/**  Doubly optional so the webhook can be cleared as well as changed. */
	webhook_url?: string | null,
	notify: NotifyPolicy | null,
	catch_up: boolean | null,
	dest_profile_id?: string | null,
};

/**  A partial update. Absent fields are left as they are. */
export type ScheduleUpdate_Serialize = {
	name: string | null,
	cron: string | null,
	timezone: ScheduleTimezone | null,
	enabled: boolean | null,
	action: ScheduleAction | null,
	/**  Doubly optional so the webhook can be cleared as well as changed. */
	webhook_url: string | null,
	notify: NotifyPolicy | null,
	catch_up: boolean | null,
	dest_profile_id: string | null,
};

/**
 *  A schedule plus the things the list view needs but the record does not hold:
 *  when it next runs, and what the cron expression means in English.
 * 
 *  Computed here rather than in TypeScript so there is exactly one cron
 *  implementation. A second one in the frontend would eventually disagree with
 *  the scheduler, and the UI would confidently show a time nothing happens at.
 */
export type ScheduleView = {
	schedule: Schedule,
	description: string,
	next_run_at: string | null,
	/**  True while a run started by this schedule is still going. */
	running: boolean,
};

/**
 *  A scheduled run finished, carrying everything the UI needs to show it.
 * 
 *  Separate from [`JobFinished`] because a scheduled run has a schedule behind
 *  it: the schedules list has to update its "last outcome" column, which a bare
 *  job id would not tell it.
 */
export type ScheduledRunFinished = RunReport;

export type SchedulerStatus = {
	/**  Whether the in-app scheduler loop is running right now. */
	running: boolean,
	in_flight: string[],
};

/**  What the UI is allowed to know about stored secrets: whether they exist. */
export type SecretStatus = {
	has_db_password: boolean,
};

/**  An off-site destination, minus its credential. */
export type SharedDestination = {
	name: string,
	kind: DestinationKind,
	retention?: RetentionPolicy,
};

/**  A sync plan, keyed to its profile by name. */
export type SharedPlan = {
	profile_name: string,
	name: string,
	database: string,
	selections: TableSelection[],
	/**
	 *  Masking rules travel with the plan.
	 * 
	 *  They describe which columns are sensitive, which is knowledge a team
	 *  wants shared — and they carry no salt: the salt is derived from a local
	 *  secret and never leaves the machine. See [`crate::mask`].
	 */
	masking?: MaskRule[],
};

/**
 *  A connection, minus the ability to connect.
 * 
 *  Identified by name rather than by id: two machines generate different ids
 *  for the same server, and an import that matched on id would duplicate
 *  everything every time.
 */
export type SharedProfile = SharedProfile_Serialize | SharedProfile_Deserialize;

/**
 *  A connection, minus the ability to connect.
 * 
 *  Identified by name rather than by id: two machines generate different ids
 *  for the same server, and an import that matched on id would duplicate
 *  everything every time.
 */
export type SharedProfile_Deserialize = {
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**  Host, port, user and database. No password — there is no field for one. */
	db: DbConfig,
	/**
	 *  The SSH connection this tunnels through, named rather than copied — so
	 *  a bundle describing six databases behind one bastion says "bastion"
	 *  six times and describes it once.
	 */
	ssh_connection?: string | null,
	/**
	 *  The inline tunnel a version 1 bundle carried.
	 * 
	 *  Read on import and never written: a bundle from an older DBSync must
	 *  not lose the tunnel it believed it was sharing. See [`import`].
	 */
	ssh?: SshConfig | null,
	tool_overrides?: ToolOverrides,
};

/**
 *  A connection, minus the ability to connect.
 * 
 *  Identified by name rather than by id: two machines generate different ids
 *  for the same server, and an import that matched on id would duplicate
 *  everything every time.
 */
export type SharedProfile_Serialize = {
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**  Host, port, user and database. No password — there is no field for one. */
	db: DbConfig,
	/**
	 *  The SSH connection this tunnels through, named rather than copied — so
	 *  a bundle describing six databases behind one bastion says "bastion"
	 *  six times and describes it once.
	 */
	ssh_connection: string | null,
	/**
	 *  The inline tunnel a version 1 bundle carried.
	 * 
	 *  Read on import and never written: a bundle from an older DBSync must
	 *  not lose the tunnel it believed it was sharing. See [`import`].
	 */
	ssh?: SshConfig | null,
	tool_overrides: ToolOverrides,
};

/**
 *  An SSH server, minus the ability to authenticate to it.
 * 
 *  Endpoint and auth *method*. A key-file path is a path, not a key, and the
 *  passphrase protecting it is in the receiver's keychain or nowhere.
 */
export type SharedSshConnection = {
	name: string,
	endpoint: SshEndpoint,
	/**
	 *  Another entry in the same list, by name — for the same reason profiles
	 *  are matched by name: ids differ between machines.
	 */
	jump_host?: string | null,
};

/**  A backup that came out dramatically smaller than the one before it. */
export type ShrinkWarning = {
	filename: string,
	at: string,
	bytes: number | null,
	previous_filename: string,
	previous_bytes: number | null,
};

/**  One artifact's size at a point in time. */
export type SizePoint = {
	at: string,
	bytes: number | null,
	filename: string,
};

export type SshAuth = 
/**  Use the running ssh-agent. Preferred: no key material touches us. */
{ kind: "agent" } | 
/**
 *  Use a private key file. `passphrase_in_keychain` records whether a
 *  passphrase was stored; the passphrase itself is never in this struct.
 */
{ kind: "key_file"; path: string; passphrase_in_keychain: boolean };

/**
 *  A route to an SSH server with its bastion resolved: what [`crate::ssh`]
 *  needs in order to actually connect.
 * 
 *  This is a *derived* value, built by [`crate::store::Store::resolve_ssh`]
 *  from a stored [`SshConnection`] and the connection it jumps through. It is
 *  deliberately not persisted in this shape any more.
 * 
 *  It does still describe the layout of the `profiles.ssh_config` column that
 *  versions before saved SSH connections wrote, which is why the endpoint stays
 *  flattened: [`adopt_legacy_configs`] parses those rows with this type.
 */
export type SshConfig = {
	/**  Optional single-hop ProxyJump. Chained jumps are out of scope for v1. */
	jump_host: SshEndpoint | null,
} & SshEndpoint;

/**  A named SSH server, reusable by any number of connection profiles. */
export type SshConnection = {
	id: string,
	/**  Unique, and what every profile and the audit log refer to it by. */
	name: string,
	endpoint: SshEndpoint,
	/**
	 *  Another saved connection used as a bastion. See the module docs for why
	 *  this is a reference.
	 */
	jump_host_id: string | null,
	created_at: string,
	updated_at: string,
};

export type SshConnectionCreate = {
	name: string,
	endpoint: SshEndpoint,
	jump_host_id?: string | null,
};

/**
 *  An SSH connection plus the two things the UI cannot derive from the record:
 *  whether its passphrase is stored, and what would break if it were deleted.
 */
export type SshConnectionStatus = {
	has_passphrase: boolean,
	/**  Names of the profiles tunnelling through it. */
	used_by_profiles: string[],
	/**  Names of the SSH connections jumping through it. */
	used_by_jump: string[],
};

/**
 *  A partial edit. An omitted field means "leave unchanged".
 * 
 *  `jump_host_id` is doubly-optional and carries the distinction by *presence*,
 *  exactly as [`crate::profile::ProfileUpdate::ssh_connection_id`] does:
 *  omitting the key keeps the current bastion, an explicit `null` removes it.
 */
export type SshConnectionUpdate = SshConnectionUpdate_Serialize | SshConnectionUpdate_Deserialize;

/**
 *  A partial edit. An omitted field means "leave unchanged".
 * 
 *  `jump_host_id` is doubly-optional and carries the distinction by *presence*,
 *  exactly as [`crate::profile::ProfileUpdate::ssh_connection_id`] does:
 *  omitting the key keeps the current bastion, an explicit `null` removes it.
 */
export type SshConnectionUpdate_Deserialize = {
	name?: string | null,
	endpoint?: SshEndpoint | null,
	jump_host_id?: string | null,
};

/**
 *  A partial edit. An omitted field means "leave unchanged".
 * 
 *  `jump_host_id` is doubly-optional and carries the distinction by *presence*,
 *  exactly as [`crate::profile::ProfileUpdate::ssh_connection_id`] does:
 *  omitting the key keeps the current bastion, an explicit `null` removes it.
 */
export type SshConnectionUpdate_Serialize = {
	name: string | null,
	endpoint: SshEndpoint | null,
	jump_host_id?: string | null,
};

export type SshEndpoint = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

/**  Result of testing a saved SSH connection on its own. */
export type SshReport = {
	ssh: StepOutcome,
	/**  Fingerprint of the key the server presented, once it is trusted. */
	host_key: string | null,
	authenticated_as: string | null,
	host_key_prompt: HostKeyPrompt | null,
};

export type StepOutcome = { status: "ok"; detail: string } | { status: "failed"; detail: string } | { status: "skipped"; detail: string };

export type SyncPlan = {
	id: string,
	profile_id: string,
	name: string,
	database: string,
	selections: TableSelection[],
	/**
	 *  Columns masked on the destination after a sync restores this plan.
	 * 
	 *  Lives here rather than on the schedule because it describes the data,
	 *  not the timing — every schedule running this plan inherits the same
	 *  protection instead of keeping a copy that can drift.
	 */
	masking?: MaskRule[],
	/**
	 *  Bumped on every save, so a plan that changed under a schedule is
	 *  visible rather than silent.
	 */
	revision: number,
	created_at: string,
	updated_at: string,
};

export type SyncPlanCreate = {
	profile_id: string,
	name: string,
	database: string,
	selections: TableSelection[],
	masking?: MaskRule[],
};

/**  Back up a source and restore it to a destination as one job. */
export type SyncRequest = {
	backup: BackupRequest,
	naming: TargetNaming,
	restore: EngineRestoreOptions,
	/**  Compare exact row counts once the restore finishes. */
	verify: boolean,
	/**
	 *  Also compare table contents and columns.
	 * 
	 *  Defaulted so a stored request written before this existed still
	 *  deserialises — an old schedule keeps its old, shallower behaviour
	 *  rather than silently acquiring a full table scan.
	 */
	deep_verify?: boolean,
	/**
	 *  Columns to mask on the destination once the restore lands.
	 * 
	 *  Defaulted so an existing stored request still deserialises. Note what
	 *  this does *not* cover: the artifact written by this run still holds the
	 *  real data. See [`crate::mask`].
	 */
	masking?: MaskRule[],
	/**  Applied to the source's backup directory after a successful run. */
	retention: RetentionPolicy | null,
	/**  Required when the destination naming strategy is destructive. */
	typed_confirmation: string | null,
};

export type TableInfo = {
	schema: string | null,
	name: string,
	/**  InnoDB/MyISAM for MySQL; `None` for PostgreSQL. */
	storage_engine: string | null,
	/**
	 *  Planner estimate. Cheap but approximate — never use it to verify a
	 *  restore. See [`crate::verify`].
	 */
	estimated_rows: number | null,
	data_bytes: number | null,
	index_bytes: number | null,
	/**
	 *  Whether a consistent snapshot is possible for this table.
	 * 
	 *  Serialised rather than left as a method so the UI cannot re-derive the
	 *  rule and drift from it — this decides whether we warn that
	 *  `--single-transaction` does not cover a selected table.
	 */
	transactional: boolean,
};

/**  What to do with one table. */
export type TableMode = 
/**  Structure and rows. */
"schema_and_data" | 
/**  Structure only — the default for everything not explicitly selected. */
"schema_only" | 
/**  Omit entirely. */
"exclude";

export type TableSelection = {
	name: string,
	mode: TableMode,
	/**  Optional row filter applied only when `mode` is `SchemaAndData`. */
	where_filter: string | null,
};

/**  How the destination database is chosen. */
export type TargetNaming = 
/**  Create `{prefix}_{YYYYMMDD_HHMMSS}`. Non-destructive; the default. */
{ strategy: "new_timestamped"; prefix: string } | 
/**  Use a fixed name, dropping it first if it exists. */
{ strategy: "drop_and_recreate"; name: string } | 
/**  Restore into an existing database without dropping. */
{ strategy: "into_existing"; name: string };

export type Tool = "mysqldump" | "mysql" | "mydumper" | "myloader" | "pg_dump" | "pg_dumpall" | "pg_restore" | "psql" | "mongodump" | "mongorestore";

/**
 *  Per-profile overrides for external client binaries.
 * 
 *  We never bundle Oracle's `mysqldump` (GPLv2); binaries are discovered on the
 *  host and may be pointed at explicitly here. See DECISIONS.md.
 */
export type ToolOverrides = {
	mysqldump: string | null,
	mysql: string | null,
	mydumper: string | null,
	myloader: string | null,
	pg_dump: string | null,
	pg_dumpall: string | null,
	pg_restore: string | null,
	psql: string | null,
	/**  Defaulted so profiles stored before MongoDB support still deserialise. */
	mongodump?: string | null,
	mongorestore?: string | null,
};

/**
 *  Where the external client binaries come from.
 * 
 *  Global rather than per-profile: this describes the machine the app is
 *  running on, not the database being talked to. A per-profile binary override
 *  still wins over whatever is set here — that one *is* about the database,
 *  which is why the two coexist.
 */
export type ToolSource = 
/**
 *  Binaries installed on this machine.
 * 
 *  The default, and the only one that works with no container runtime
 *  present. Changing the default would silently re-route every existing
 *  install through Docker.
 */
{ kind: "local" } | 
/**
 *  Borrow the binaries from a container that is already running.
 * 
 *  Nothing to download when a database container is already there, and the
 *  most fragile of the three: it stops working the moment that container
 *  is stopped or replaced, and the client version is whatever that image
 *  happens to ship.
 */
{ kind: "docker_exec"; container: string; 
/**
 *  Directory holding the binaries inside the container. `None` means
 *  they are on the container's `PATH`, which is the usual case.
 */
bin_dir?: string | null } | 
/**
 *  Run a throwaway container from an image, one per invocation.
 * 
 *  Costs an image pull once and then always has the right client, with no
 *  dependency on anything else still running.
 */
{ kind: "docker_run"; image: string };

/**  What discovery found for one tool, in the shape the settings page needs. */
export type ToolStatus = {
	tool: Tool,
	binary: string,
	/**  How it would be invoked — a host path, or a `docker …` line. */
	location: string | null,
	version: string | null,
	/**  Whether its absence stops an engine working at all. */
	required: boolean,
	/**  The Homebrew formula that would provide it, if Homebrew is available. */
	brew_formula: string | null,
};

/**
 *  The compact form of a verification, for people rather than for diffing.
 * 
 *  The counts are exported to TypeScript as `number`. specta refuses to emit
 *  `usize` as anything else, and rightly: JS has no 64-bit integer. A table
 *  count that needed one would be a bigger problem than its representation.
 */
export type VerificationSummary = {
	passed: boolean,
	tables_checked: number | null,
	failures: number | null,
	skipped: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

