// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listProfiles: () => typedError<ConnectionProfile[], CommandError>(__TAURI_INVOKE("list_profiles")),
	getProfile: (id: string) => typedError<{
	id: string,
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**  `None` means connect directly, without a tunnel. */
	ssh: SshConfig | null,
	db: DbConfig,
	tool_overrides: ToolOverrides,
	created_at: string,
	updated_at: string,
} | null, CommandError>(__TAURI_INVOKE("get_profile", { id })),
	/**
	 *  Create a profile, optionally storing its database password in the keychain.
	 * 
	 *  The password is consumed here and never echoed back.
	 */
	createProfile: (input: ProfileCreate, dbPassword: string | null) => typedError<ConnectionProfile, CommandError>(__TAURI_INVOKE("create_profile", { input, dbPassword })),
	updateProfile: (id: string, patch: ProfileUpdate_Deserialize) => typedError<ConnectionProfile, CommandError>(__TAURI_INVOKE("update_profile", { id, patch })),
	/**  Delete a profile and purge every secret belonging to it. */
	deleteProfile: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_profile", { id })),
	/**  Store or clear a profile secret. An empty value clears it. */
	setProfileSecret: (id: string, kind: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_profile_secret", { id, kind, value })),
	/**  Report whether secrets exist — never their values. */
	profileSecretStatus: (id: string) => typedError<SecretStatus, CommandError>(__TAURI_INVOKE("profile_secret_status", { id })),
	/**
	 *  Test a profile, reporting each step separately.
	 * 
	 *  Never returns `Err` for an unreachable server: a failed *connection* is a
	 *  successful *test*, and the per-step detail is the whole point.
	 */
	testConnection: (id: string) => typedError<ConnectionReport, CommandError>(__TAURI_INVOKE("test_connection", { id })),
	/**
	 *  Pin a host key after the user has verified its fingerprint.
	 * 
	 *  `replace` must be set explicitly when a *different* key was already pinned —
	 *  silently overwriting is indistinguishable from accepting a MITM.
	 */
	trustHostKey: (hostPort: string, algorithm: string, fingerprint: string, replace: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("trust_host_key", { hostPort, algorithm, fingerprint, replace })),
	/**  List the databases visible to a profile's user. */
	listDatabases: (id: string) => typedError<DatabaseInfo[], CommandError>(__TAURI_INVOKE("list_databases", { id })),
	/**  List the tables in one database, with the metadata the picker needs. */
	listTables: (id: string, database: string) => typedError<TableInfo[], CommandError>(__TAURI_INVOKE("list_tables", { id, database })),
	/**
	 *  Start a backup and return its job id immediately.
	 * 
	 *  The work runs in the background; progress arrives as `JobProgress` events
	 *  and the terminal state as `JobFinished`. Blocking the command until the dump
	 *  finished would freeze the UI for the length of the job.
	 */
	startBackup: (profileId: string, request: BackupRequest) => typedError<string, CommandError>(__TAURI_INVOKE("start_backup", { profileId, request })),
	/**  Start a source-to-destination sync and return its job id. */
	startSync: (sourceId: string, destId: string, request: SyncRequest) => typedError<string, CommandError>(__TAURI_INVOKE("start_sync", { sourceId, destId, request })),
	listSyncPlans: (profileId: string) => typedError<SyncPlan[], CommandError>(__TAURI_INVOKE("list_sync_plans", { profileId })),
	createSyncPlan: (input: SyncPlanCreate) => typedError<SyncPlan, CommandError>(__TAURI_INVOKE("create_sync_plan", { input })),
	updateSyncPlan: (id: string, selections: TableSelection[]) => typedError<SyncPlan, CommandError>(__TAURI_INVOKE("update_sync_plan", { id, selections })),
	deleteSyncPlan: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_sync_plan", { id })),
	/**
	 *  Parse a legacy `tables.conf` into selections.
	 * 
	 *  Lets an existing Bash-tool setup be carried over without retyping a couple
	 *  of hundred table names.
	 */
	importTablesConf: (contents: string) => typedError<TableSelection[], CommandError>(__TAURI_INVOKE("import_tables_conf", { contents })),
	/**  Start a restore and return its job id immediately. */
	startRestore: (profileId: string, request: RestoreRequest) => typedError<string, CommandError>(__TAURI_INVOKE("start_restore", { profileId, request })),
	backupDirectory: () => typedError<string, CommandError>(__TAURI_INVOKE("backup_directory")),
	listArtifacts: (directory: string | null) => typedError<Artifact[], CommandError>(__TAURI_INVOKE("list_artifacts", { directory })),
	/**  Hash an artifact and compare it against its manifest. */
	checkArtifact: (path: string) => typedError<IntegrityCheck, CommandError>(__TAURI_INVOKE("check_artifact", { path })),
	/**  Delete an artifact and its manifest. */
	deleteArtifact: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_artifact", { path })),
	listJobs: (limit: number) => typedError<JobRecord[], CommandError>(__TAURI_INVOKE("list_jobs", { limit })),
	/**
	 *  Cancel a running job.
	 * 
	 *  This signals the job's `CancellationToken`, which propagates into its child
	 *  processes and tunnels. Returns false when the job is not running.
	 */
	cancelJob: (jobId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("cancel_job", { jobId })),
	activeJobIds: () => typedError<string[], CommandError>(__TAURI_INVOKE("active_job_ids")),
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
};

/** Events */
export const events = {
	jobFinished: makeEvent<JobFinished>("job-finished"),
	jobProgress: makeEvent<JobProgress>("job-progress"),
};

/* Types */
export type AppInfo = {
	engine_version: string,
	store_path: string,
};

/**  One artifact, as the library lists it. */
export type Artifact = {
	path: string,
	filename: string,
	size_bytes: number | null,
	modified_at: string,
	/**  Populated when a readable manifest sits beside the artifact. */
	database: string | null,
	engine: Engine | null,
	source_profile_name: string | null,
	table_count: number | null,
	tables_with_data: number | null,
	/**  `None` when there is no manifest to check against. */
	has_manifest: boolean,
};

export type BackupRequest = {
	common: CommonBackupOptions,
	engine: EngineBackupOptions,
};

/**
 *  Error shape crossing into the webview.
 * 
 *  Carries a human-readable message and a machine-readable kind so the UI can
 *  react (e.g. highlight a duplicate name field) without string matching.
 */
export type CommandError = {
	kind: string,
	message: string,
};

export type CommonBackupOptions = {
	database: string,
	selections: TableSelection[],
	output_dir: string,
	/**  Gzip the stream. Ignored for formats that compress internally. */
	compress: boolean,
	/**
	 *  Encrypt at rest with age. Wired in a later milestone; the manifest
	 *  already records the flag.
	 */
	encrypt: boolean,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	/**  `None` means connect directly, without a tunnel. */
	ssh: SshConfig | null,
	db: DbConfig,
	tool_overrides: ToolOverrides,
	created_at: string,
	updated_at: string,
};

/**  Step-by-step result of testing a profile. */
export type ConnectionReport = {
	ssh: StepOutcome,
	tunnel: StepOutcome,
	db_ping: StepOutcome,
	catalog_read: StepOutcome,
	server_version: string | null,
	/**
	 *  Present when the connection stopped on an unverified host key. The UI
	 *  shows the fingerprint and, if the user accepts, pins it and retries.
	 */
	host_key_prompt: HostKeyPrompt | null,
};

export type DatabaseInfo = {
	name: string,
	charset: string | null,
	collation: string | null,
};

/**
 *  Database coordinates *as seen from the SSH host* (or from this machine when
 *  `ConnectionProfile::ssh` is `None`).
 */
export type DbConfig = {
	host: string,
	port: number,
	user: string,
	database: string | null,
};

/**
 *  A supported database engine.
 * 
 *  The serde representation is snake_case and is the *single* source of truth
 *  for how these values are written to SQLite and to JSON manifests. Do not
 *  hand-write match arms mapping these to strings — use `Display`/`FromStr`.
 */
export type Engine = "mysql" | "postgres";

export type EngineBackupOptions = {
	engine: "mysql",
} & MysqlBackupOptions | {
	engine: "postgres",
} & PostgresBackupOptions;

export type EngineRestoreOptions = {
	engine: "mysql",
} & MysqlRestoreOptions | {
	engine: "postgres",
} & PostgresRestoreOptions;

/**
 *  Environment classification for a connection profile.
 * 
 *  Drives colour-coding in the UI and the strictness of destructive-action
 *  confirmations — production targets require typed confirmation.
 */
export type EnvironmentTag = "prod" | "staging" | "dev";

/**  An unverified host key the user must decide about. */
export type HostKeyPrompt = {
	host_port: string,
	algorithm: string,
	fingerprint: string,
	/**
	 *  True when a *different* key was previously pinned. Far more serious
	 *  than first contact: it is what a machine-in-the-middle looks like.
	 */
	changed: boolean,
	/**  The fingerprint we had pinned, when `changed`. */
	previous_fingerprint: string | null,
};

/**  Result of checking an artifact against its manifest. */
export type IntegrityCheck = { status: "ok" } | { status: "mismatch"; expected: string; actual: string } | { status: "no_manifest" } | { status: "unreadable"; detail: string };

/**
 *  Emitted when a job reaches a terminal state, so the UI can refresh history
 *  without polling.
 */
export type JobFinished = {
	job_id: string,
	outcome: string,
};

export type JobKind = "backup" | "restore" | "verify" | "sync";

export type JobOutcome = "success" | "failed" | "cancelled";

export type JobPhase = "initializing" | "ssh_connect" | "tunneling" | "introspect" | "dump_schema" | "dump_data" | "compress" | "transfer" | "restore" | "verify" | "cleanup" | "done";

/**  One progress record from a running job. */
export type JobProgress = ProgressEvent;

/**  The persisted record of one job run. */
export type JobRecord = {
	id: string,
	kind: JobKind,
	source_profile_id: string,
	dest_profile_id: string | null,
	started_at: string,
	finished_at: string | null,
	outcome: JobOutcome | null,
	artifact_path: string | null,
	/**
	 *  Serialised options, kept opaque so option shapes can evolve without a
	 *  schema migration.
	 */
	options_json: string,
	/**
	 *  Durable log. Accumulated from the event stream by [`JobContext`] — the
	 *  broadcast channel is lossy and must never be the only record.
	 */
	log: string,
};

export type LogLevel = "debug" | "info" | "warn" | "error";

export type MysqlBackupOptions = {
	/**  Consistent snapshot without locking. Only meaningful for InnoDB. */
	single_transaction: boolean,
	/**  Emit binary columns as hex. Without this, BLOBs can corrupt in transit. */
	hex_blob: boolean,
	set_gtid_purged_off: boolean,
	add_drop_table: boolean,
	extended_insert: boolean,
	routines: boolean,
	triggers: boolean,
	events: boolean,
	default_character_set: string,
	/**
	 *  Send `--column-statistics=0`, required when an 8.x client talks to a
	 *  pre-8.0 server.
	 */
	disable_column_statistics: boolean,
	/**  Strip `DEFINER=` clauses so restores need no SUPER privilege. */
	strip_definer: boolean,
	/**  Use mydumper for a parallel dump when the binary is available. */
	parallel_threads: number | null,
	extra_flags: string[],
};

export type MysqlRestoreOptions = {
	foreign_key_checks_off: boolean,
	unique_checks_off: boolean,
	autocommit_off: boolean,
	/**  Skip writing the restore to the destination's binary log. */
	disable_binlog: boolean,
	charset: string,
	collation: string,
};

export type PgDumpFormat = 
/**
 *  `-Fc`. Default: the only format supporting both selective and parallel
 *  restore.
 */
"custom" | 
/**  `-Fd`. Adds parallel *dump*. */
"directory" | 
/**  `-Fp`. Plain SQL; no selective restore. */
"plain";

export type PostgresBackupOptions = {
	format: PgDumpFormat,
	no_owner: boolean,
	no_privileges: boolean,
	blobs: boolean,
	/**  Restrict to these schemas; empty means all. */
	schemas: string[],
	serializable_deferrable: boolean,
	/**  Parallel dump jobs. Only honoured for `Directory`. */
	parallel_jobs: number | null,
	/**  Additionally dump roles/globals via `pg_dumpall --globals-only`. */
	include_globals: boolean,
	extra_flags: string[],
};

export type PostgresRestoreOptions = {
	no_owner: boolean,
	no_privileges: boolean,
	/**  `pg_restore -j`. Only valid for archive formats. */
	parallel_jobs: number | null,
	/**  Restore only these tables. Requires an archive format. */
	only_tables: string[],
	clean: boolean,
};

export type ProfileCreate = {
	name: string,
	engine: Engine,
	environment: EnvironmentTag,
	ssh: SshConfig | null,
	db: DbConfig,
	tool_overrides?: ToolOverrides,
};

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh` is doubly-optional on purpose, and the distinction is carried by
 *  *presence*, not by value: omitting the key leaves the SSH config alone,
 *  while sending an explicit `null` clears it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate = ProfileUpdate_Serialize | ProfileUpdate_Deserialize;

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh` is doubly-optional on purpose, and the distinction is carried by
 *  *presence*, not by value: omitting the key leaves the SSH config alone,
 *  while sending an explicit `null` clears it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate_Deserialize = {
	name?: string | null,
	engine?: Engine | null,
	environment?: EnvironmentTag | null,
	ssh?: SshConfig | null,
	db?: DbConfig | null,
	tool_overrides?: ToolOverrides | null,
};

/**
 *  Patch for an existing profile. An omitted field means "leave unchanged".
 * 
 *  `ssh` is doubly-optional on purpose, and the distinction is carried by
 *  *presence*, not by value: omitting the key leaves the SSH config alone,
 *  while sending an explicit `null` clears it. Every field is
 *  `#[serde(default)]` so that omission is legal and so the generated
 *  TypeScript renders them as optional — without it the frontend would be
 *  forced to send every key and could never express "leave unchanged".
 */
export type ProfileUpdate_Serialize = {
	name: string | null,
	engine: Engine | null,
	environment: EnvironmentTag | null,
	ssh?: SshConfig | null,
	db: DbConfig | null,
	tool_overrides: ToolOverrides | null,
};

/**
 *  A single point-in-time progress record.
 * 
 *  Every field beyond `job_id`/`ts`/`phase`/`level`/`message` is optional
 *  because different phases have different meaningful measurements: a schema
 *  dump reports bytes, a data dump reports per-table counts.
 */
export type ProgressEvent = {
	job_id: string,
	ts: string,
	phase: JobPhase,
	level: LogLevel,
	message: string,
	table: string | null,
	bytes_done: number | null,
	bytes_total: number | null,
	rows: number | null,
	percent: number | null,
};

export type RestoreRequest = {
	artifact_path: string,
	naming: TargetNaming,
	engine: EngineRestoreOptions,
	/**  Verify the artifact checksum before touching the destination. */
	verify_checksum: boolean,
	/**  Typed confirmation supplied by the user for a destructive restore. */
	typed_confirmation: string | null,
};

export type RetentionPolicy = {
	/**  Keep at most this many of the most recent artifacts. */
	keep_last: number | null,
	/**  Delete artifacts older than this many days. */
	max_age_days: number | null,
};

/**  What the UI is allowed to know about stored secrets: whether they exist. */
export type SecretStatus = {
	has_db_password: boolean,
	has_ssh_passphrase: boolean,
};

export type SshAuth = 
/**  Use the running ssh-agent. Preferred: no key material touches us. */
{ kind: "agent" } | 
/**
 *  Use a private key file. `passphrase_in_keychain` records whether a
 *  passphrase was stored; the passphrase itself is never in this struct.
 */
{ kind: "key_file"; path: string; passphrase_in_keychain: boolean };

export type SshConfig = {
	/**  Optional single-hop ProxyJump. Chained jumps are out of scope for v1. */
	jump_host: SshEndpoint | null,
} & SshEndpoint;

export type SshEndpoint = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

export type StepOutcome = { status: "ok"; detail: string } | { status: "failed"; detail: string } | { status: "skipped"; detail: string };

export type SyncPlan = {
	id: string,
	profile_id: string,
	name: string,
	database: string,
	selections: TableSelection[],
	/**
	 *  Bumped on every save, so a plan that changed under a schedule is
	 *  visible rather than silent.
	 */
	revision: number,
	created_at: string,
	updated_at: string,
};

export type SyncPlanCreate = {
	profile_id: string,
	name: string,
	database: string,
	selections: TableSelection[],
};

/**  Back up a source and restore it to a destination as one job. */
export type SyncRequest = {
	backup: BackupRequest,
	naming: TargetNaming,
	restore: EngineRestoreOptions,
	/**  Compare exact row counts once the restore finishes. */
	verify: boolean,
	/**  Applied to the source's backup directory after a successful run. */
	retention: RetentionPolicy | null,
	/**  Required when the destination naming strategy is destructive. */
	typed_confirmation: string | null,
};

export type TableInfo = {
	schema: string | null,
	name: string,
	/**  InnoDB/MyISAM for MySQL; `None` for PostgreSQL. */
	storage_engine: string | null,
	/**
	 *  Planner estimate. Cheap but approximate — never use it to verify a
	 *  restore. See [`crate::verify`].
	 */
	estimated_rows: number | null,
	data_bytes: number | null,
	index_bytes: number | null,
	/**
	 *  Whether a consistent snapshot is possible for this table.
	 * 
	 *  Serialised rather than left as a method so the UI cannot re-derive the
	 *  rule and drift from it — this decides whether we warn that
	 *  `--single-transaction` does not cover a selected table.
	 */
	transactional: boolean,
};

/**  What to do with one table. */
export type TableMode = 
/**  Structure and rows. */
"schema_and_data" | 
/**  Structure only — the default for everything not explicitly selected. */
"schema_only" | 
/**  Omit entirely. */
"exclude";

export type TableSelection = {
	name: string,
	mode: TableMode,
	/**  Optional row filter applied only when `mode` is `SchemaAndData`. */
	where_filter: string | null,
};

/**  How the destination database is chosen. */
export type TargetNaming = 
/**  Create `{prefix}_{YYYYMMDD_HHMMSS}`. Non-destructive; the default. */
{ strategy: "new_timestamped"; prefix: string } | 
/**  Use a fixed name, dropping it first if it exists. */
{ strategy: "drop_and_recreate"; name: string } | 
/**  Restore into an existing database without dropping. */
{ strategy: "into_existing"; name: string };

/**
 *  Per-profile overrides for external client binaries.
 * 
 *  We never bundle Oracle's `mysqldump` (GPLv2); binaries are discovered on the
 *  host and may be pointed at explicitly here. See DECISIONS.md.
 */
export type ToolOverrides = {
	mysqldump: string | null,
	mysql: string | null,
	mydumper: string | null,
	myloader: string | null,
	pg_dump: string | null,
	pg_dumpall: string | null,
	pg_restore: string | null,
	psql: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

